[alembic]
script_location = %(here)s/alembic_tenant
prepend_sys_path = .


[post_write_hooks]
# Automatically replace hardcoded schemas with resolve_schema() calls
hooks = process_tenant_schema
process_tenant_schema.type = exec
process_tenant_schema.executable = python
process_tenant_schema.options = chalicelib/alembic_tenant/post_write_hook.py REVISION_SCRIPT_FILENAME


[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
