from datetime import datetime, timedelta

from freezegun import freeze_time
from sqlalchemy.orm import Session

from chalicelib.new.query.domain.enums.download_type import DownloadType
from chalicelib.new.query.domain.enums.query_state import QueryState
from chalicelib.new.query.domain.enums.request_type import RequestType
from chalicelib.new.query.domain.get_chunks_no_cfdi_ws_query_processed import (
    get_chunks_no_ws_query_processed,
)
from chalicelib.new.query.domain.query_cfdi_splitter import get_cfdi_chunks
from chalicelib.new.query.domain.query_creator import last_X_fiscal_years
from chalicelib.new.utils.datetime import mx_now
from chalicelib.schema.models.company import Company
from chalicelib.schema.models.tenant.cfdi import CFDI
from chalicelib.schema.models.tenant.sat_query import SATQuery


def dates_close(d1: datetime, d2: datetime, delta: timedelta = timedelta(seconds=1)):
    return abs(d1 - d2) <= delta


@freeze_time("2026-01-02")
def test_complete_cfdis_generate_chunks(
    company_session: Session,
    company: Company,
):
    start = datetime.fromisoformat("2025-01-01")
    end = mx_now()
    download_type = DownloadType.ISSUED

    assert company_session.query(CFDI).count() == 0, "This test asume no CFDI created"
    assert (
        company_session.query(SATQuery)
        .filter(
            SATQuery.download_type == download_type,
            SATQuery.request_type == RequestType.CFDI,
            SATQuery.state == QueryState.PROCESSED,
        )
        .count()
        == 0
    ), "This test asume no request are processed, ergo, needs to create requests"

    # Test
    chunks = get_cfdi_chunks(
        company_session=company_session,
        company_identifier=company.identifier,
        download_type=download_type,
        start=start,
        end=end,
    )

    # Check results
    first_query = chunks[0]
    last_query = chunks[-1]

    assert dates_close(first_query.start, start)
    assert dates_close(last_query.end, end)


@freeze_time("2026-08-12")
def test_complete_cfdis_generate_chunks_need_xml(
    company_session: Session,
    company: Company,
):
    start = last_X_fiscal_years(years=5)
    end = mx_now()
    download_type = DownloadType.ISSUED
    cfdi_need_xml = CFDI.demo(
        is_issued=download_type.to_bool(),
        Estatus=True,
        Fecha=datetime.fromisoformat("2025-08-08"),
    )

    assert not cfdi_need_xml.xml_content, "This test is to complete this XML need"
    company_session.add(cfdi_need_xml)

    assert company_session.query(CFDI).count() == 1, (
        "This test asume only the cfdi_need_xml is created"
    )
    sat_query_cfdi = SATQuery(
        download_type=download_type,
        request_type=RequestType.CFDI,
        state=QueryState.PROCESSED,
        start=end,
        end=end,
    )
    company_session.add(sat_query_cfdi)

    # Test
    chunks = get_cfdi_chunks(
        company_session=company_session,
        company_identifier=company.identifier,
        download_type=download_type,
        start=start,
        end=end,
    )

    # Check results
    chunks = sorted(chunks)

    assert len(chunks) > 1, "Must be one for the CFDI and other generated by holes in WS"

    assert (
        len(
            [
                chunk
                for chunk in chunks
                if dates_close(chunk.start, cfdi_need_xml.Fecha)
                and dates_close(chunk.end, cfdi_need_xml.Fecha)
            ]
        )
        == 1
    ), "One chunk needs to cover only the CFDI"


def test_get_chunks_no_cfdi_ws_query_processed(company_session: Session):
    start = datetime.fromisoformat("2025-01-01")
    end = datetime.fromisoformat("2025-10-14")
    download_type = DownloadType.ISSUED
    _chunks = get_chunks_no_ws_query_processed(company_session, start, end, download_type)


# Suite de pruebas para get_chunks_no_cfdi_ws_query_processed


@freeze_time("2025-06-01 12:00:00")
def test_no_queries_returns_full_range_chunks(company_session: Session):
    """Sin queries procesadas, debe retornar chunks que cubran todo el rango."""
    start = datetime(2025, 1, 1)
    end = datetime(2025, 1, 31)
    download_type = DownloadType.ISSUED
    chunk_size = timedelta(days=10)

    chunks = get_chunks_no_ws_query_processed(
        company_session, start, end, download_type, chunk_size=chunk_size
    )

    assert len(chunks) > 0, "Should generate chunks for the full range"
    assert chunks[0].start == start, "First chunk should start at range start"
    assert chunks[-1].end == end, "Last chunk should end at range end"


@freeze_time("2025-06-01 12:00:00")
def test_non_processed_queries_ignored(company_session: Session):
    """Queries que no están en estado PROCESSED deben ser ignoradas."""
    start = datetime(2025, 1, 1)
    end = datetime(2025, 1, 31)
    download_type = DownloadType.ISSUED
    chunk_size = timedelta(days=10)

    # Crear queries en diferentes estados (no PROCESSED)
    for state in [QueryState.DRAFT, QueryState.SENT, QueryState.DOWNLOADED]:
        query = SATQuery(
            download_type=download_type,
            request_type=RequestType.CFDI,
            state=state,
            start=datetime(2025, 1, 5),
            end=datetime(2025, 1, 15),
        )
        company_session.add(query)
    company_session.flush()

    chunks = get_chunks_no_ws_query_processed(
        company_session, start, end, download_type, chunk_size=chunk_size
    )

    # Debe retornar el rango completo porque las queries no están procesadas
    assert len(chunks) == (end - start) / chunk_size, (
        "Should cover full range as no queries are PROCESSED"
    )
    assert chunks[0].start == start
    assert chunks[-1].end == end
    assert all(c.end - c.start <= chunk_size for c in chunks)


@freeze_time("2025-06-01 12:00:00")
def test_contiguous_processed_queries_create_gaps(company_session: Session):
    """Queries procesadas contiguas deben crear un solo gap cubierto."""
    start = datetime(2025, 1, 1)
    end = datetime(2025, 1, 31)
    download_type = DownloadType.ISSUED
    chunk_size = timedelta(days=1)

    # Crear queries procesadas contiguas que cubren del 10 al 20
    query1 = SATQuery(
        download_type=download_type,
        request_type=RequestType.CFDI,
        state=QueryState.PROCESSED,
        start=datetime(2025, 1, 10),
        end=datetime(2025, 1, 30),
    )

    query2 = SATQuery(
        download_type=download_type,
        request_type=RequestType.CFDI,
        state=QueryState.PROCESSED,
        start=datetime(2025, 1, 15),
        end=datetime(2025, 1, 20),
    )

    company_session.add_all([query1, query2])
    company_session.flush()

    chunks = get_chunks_no_ws_query_processed(
        company_session, start, end, download_type, chunk_size=chunk_size
    )

    # Debe haber gaps antes y después del rango cubierto
    assert len(chunks) > 0
    # Verificar que no hay chunks en el rango cubierto (10-20)
    chunks_in_covered_range = [
        c for c in chunks if c.start >= datetime(2025, 1, 10) and c.end <= datetime(2025, 1, 20)
    ]
    assert len(chunks_in_covered_range) == 0, "Should not have chunks in the covered range"


@freeze_time("2025-06-01 12:00:00")
def test_overlapping_queries_merge_coverage(company_session: Session):
    """Queries con overlap deben fusionar la cobertura."""
    start = datetime(2025, 1, 1)
    end = datetime(2025, 1, 31)
    download_type = DownloadType.ISSUED
    chunk_size = timedelta(days=5)

    # Crear queries con overlap
    query1 = SATQuery()
    query1.download_type = download_type
    query1.request_type = RequestType.CFDI
    query1.state = QueryState.PROCESSED
    query1.start = datetime(2025, 1, 10)
    query1.end = datetime(2025, 1, 18)

    query2 = SATQuery()
    query2.download_type = download_type
    query2.request_type = RequestType.CFDI
    query2.state = QueryState.PROCESSED
    query2.start = datetime(2025, 1, 15)
    query2.end = datetime(2025, 1, 22)

    company_session.add_all([query1, query2])
    company_session.flush()

    chunks = get_chunks_no_ws_query_processed(
        company_session, start, end, download_type, chunk_size=chunk_size
    )

    # Verificar que el overlap está cubierto y no genera chunks duplicados
    assert len(chunks) > 0
    chunks_in_overlap = [
        c for c in chunks if c.start >= datetime(2025, 1, 15) and c.end <= datetime(2025, 1, 18)
    ]
    assert len(chunks_in_overlap) == 0, "Overlap should be covered, no chunks needed"


@freeze_time("2025-06-01 12:00:00")
def test_queries_with_gaps_generate_intermediate_chunks(company_session: Session):
    """Queries con gaps entre ellas deben generar chunks intermedios."""
    start = datetime(2025, 1, 1)
    end = datetime(2025, 1, 31)
    download_type = DownloadType.ISSUED
    chunk_size = timedelta(days=3)

    # Crear queries con gaps: 5-8 y 15-18 (gap de 7 días entre ellas)
    query1 = SATQuery()
    query1.download_type = download_type
    query1.request_type = RequestType.CFDI
    query1.state = QueryState.PROCESSED
    query1.start = datetime(2025, 1, 5)
    query1.end = datetime(2025, 1, 8)

    query2 = SATQuery()
    query2.download_type = download_type
    query2.request_type = RequestType.CFDI
    query2.state = QueryState.PROCESSED
    query2.start = datetime(2025, 1, 15)
    query2.end = datetime(2025, 1, 18)

    company_session.add_all([query1, query2])
    company_session.flush()

    chunks = get_chunks_no_ws_query_processed(
        company_session, start, end, download_type, chunk_size=chunk_size
    )

    # Debe haber chunks en el gap intermedio (8-15)
    gap_chunks = [
        c for c in chunks if c.start >= datetime(2025, 1, 8) and c.end <= datetime(2025, 1, 15)
    ]
    assert len(gap_chunks) > 0, "Should generate chunks for the gap between queries"

    # Debe haber chunks iniciales (1-5)
    initial_chunks = [
        c for c in chunks if c.start >= datetime(2025, 1, 1) and c.end <= datetime(2025, 1, 5)
    ]
    assert len(initial_chunks) > 0, "Should generate chunks before first query"

    # Debe haber chunks finales (18-31)
    final_chunks = [
        c for c in chunks if c.start >= datetime(2025, 1, 18) and c.end <= datetime(2025, 1, 31)
    ]
    assert len(final_chunks) > 0, "Should generate chunks after last query"


@freeze_time("2025-06-01 12:00:00")
def test_coverage_buffer_respects_query_age(company_session: Session):
    """El coverage_buffer debe excluir queries muy recientes."""
    start = datetime(2025, 1, 1)
    end = datetime(2025, 1, 31)
    download_type = DownloadType.ISSUED
    chunk_size = timedelta(days=5)
    coverage_buffer = timedelta(days=3)

    # Query procesada muy recientemente (created_at muy cerca del rango)
    # Con freezegun en 2025-06-01, created_at será 2025-06-01
    query = SATQuery(
        download_type=download_type,
        request_type=RequestType.CFDI,
        state=QueryState.PROCESSED,
        start=datetime(2025, 1, 10),
        end=datetime(2025, 1, 20),
    )
    company_session.add(query)
    company_session.flush()

    chunks = get_chunks_no_ws_query_processed(
        company_session,
        start,
        end,
        download_type,
        coverage_buffer=coverage_buffer,
        chunk_size=chunk_size,
    )

    # El buffer debe reducir el rango cubierto por la query
    # La query cubre menos porque created_at - buffer reduce covered_end
    assert len(chunks) > 0


@freeze_time("2025-06-01 12:00:00")
def test_different_download_types_isolated(company_session: Session):
    """Queries de diferente download_type deben estar aisladas."""
    start = datetime(2025, 1, 1)
    end = datetime(2025, 1, 31)
    chunk_size = timedelta(days=5)

    # Crear query ISSUED procesada
    query_issued = SATQuery()
    query_issued.download_type = DownloadType.ISSUED
    query_issued.request_type = RequestType.CFDI
    query_issued.state = QueryState.PROCESSED
    query_issued.start = datetime(2025, 1, 10)
    query_issued.end = datetime(2025, 1, 20)
    company_session.add(query_issued)
    company_session.flush()

    # Consultar para RECEIVED no debe considerar la query ISSUED
    chunks_received = get_chunks_no_ws_query_processed(
        company_session, start, end, DownloadType.RECEIVED, chunk_size=chunk_size
    )

    # Debe retornar el rango completo porque no hay queries RECEIVED
    assert len(chunks_received) > 0
    assert chunks_received[0].start == start
