from datetime import datetime

from sqlalchemy.orm import Session

from chalicelib.controllers.cfdi import CFDIController
from chalicelib.schema.models.tenant.cfdi import CFDI
from chalicelib.schema.models.tenant.nomina import Nomina


def test_relationships_nomina_receptor(company_session: Session):
    cfdi = CFDI.demo()
    nomina = Nomina(
        cfdi_uuid=cfdi.UUID,
        # demo
        Version="1.2",
        TipoNomina="O",
        FechaPago=datetime.utcnow(),
        FechaInicialPago=datetime.utcnow(),
        FechaFinalPago=datetime.utcnow(),
        NumDiasPagados=15,
        ReceptorCurp="XEXX010101HNEXXXA4",
        ReceptorTipoContrato="01",
        ReceptorTipoRegimen="02",
        ReceptorNumEmpleado="EMP001",
        ReceptorPeriodicidadPago="04",
        ReceptorClaveEntFed="DIF",
    )
    company_session.add_all([cfdi, nomina])
    res = CFDIController._search(
        domain=[],
        fields=[
            "FechaCancelacion",
            "from_xml",
            "Serie",
            "Folio",
            "TipoDeComprobante",
            "c_tipo_de_comprobante.name",
            "PaymentDate",
            "ExcludeFromIVA",
            "ExcludeFromISR",
            "Fecha",
            "UUID",
            "NombreEmisor",
            "RfcEmisor",
            "LugarExpedicion",
            "RegimenFiscalEmisor",
            "c_regimen_fiscal_emisor.name",
            "RegimenFiscalReceptor",
            "c_regimen_fiscal_receptor.name",
            "DomicilioFiscalReceptor",
            "NombreReceptor",
            "RfcReceptor",
            "NoCertificado",
            "Moneda",
            "c_moneda.name",
            "FormaPago",
            "c_forma_pago.name",
            "MetodoPago",
            "c_metodo_pago.name",
            "UsoCFDIReceptor",
            "c_uso_cfdi.name",
            "Version",
            "Conceptos",
            "SubTotal",
            "Total",
            "Descuento",
            "TrasladosIEPS",
            "TrasladosISR",
            "TrasladosIVA",
            "RetencionesIEPS",
            "RetencionesISR",
            "RetencionesIVA",
            "Estatus",
            "is_issued",
            "FechaFiltro",
            "nomina.ReceptorTipoRegimen",
            "nomina.TotalPercepciones",
            "nomina.TotalDeducciones",
            "nomina.TotalOtrosPagos",
            "nomina.PercepcionesTotalSueldos",
            "nomina.OtrasPercepciones",
            "nomina.PercepcionesTotalGravado",
            "nomina.PercepcionesTotalExento",
            "nomina.AjusteISRRetenido",
            "nomina.DeduccionesTotalImpuestosRetenidos",
            "nomina.DeduccionesTotalOtrasDeducciones",
            "nomina.SubsidioCausado",
            "nomina.NetoAPagar",
            "nomina.Version",
            "nomina.TipoNomina",
            "nomina.FechaInicialPago",
            "nomina.FechaFinalPago",
            "nomina.NumDiasPagados",
            "nomina.EmisorRegistroPatronal",
            "nomina.ReceptorCurp",
            "nomina.ReceptorNumSeguridadSocial",
            "nomina.ReceptorFechaInicioRelLaboral",
            "nomina.ReceptorAntigüedad",
            "nomina.ReceptorTipoContrato",
            "nomina.ReceptorSindicalizado",
            "nomina.ReceptorTipoJornada",
            "nomina.ReceptorNumEmpleado",
            "nomina.ReceptorDepartamento",
            "nomina.ReceptorPuesto",
            "nomina.ReceptorRiesgoPuesto",
            "nomina.ReceptorPeriodicidadPago",
            "nomina.ReceptorBanco",
            "nomina.ReceptorCuentaBancaria",
            "nomina.ReceptorSalarioBaseCotApor",
            "nomina.ReceptorSalarioDiarioIntegrado",
            "nomina.ReceptorClaveEntFed",
            "Sello",
            "nomina.PercepcionesSeparacionIndemnizacion",
            "nomina.PercepcionesJubilacionPensionRetiro",
            "nomina.FechaPago",
            "nomina.c_ReceptorPeriodicidadPago.name",
            "nomina.c_ReceptorBanco.name",
            "DomicilioFiscalReceptor",
            "CfdiRelacionados",
            "is_too_big",
        ],
        session=company_session,
    )
    assert res
