import os
from datetime import timedelta

MAX_DELAY = timedelta(minutes=15)
# Verify re-queue: allow up to 60m scheduled delay on Azure; SQS path still caps via ``MAX_DELAY`` in ``SQSHandler``.
VERIFY_QUERY_MAX_DELAY = timedelta(
    minutes=int(os.environ.get("VERIFY_QUERY_MAX_DELAY_MINUTES", 60))
)
MIN_DELAY = timedelta(seconds=1)
KILOBYTE = 1024
MAX_SQS_MESSAGE_SIZE = 256 * KILOBYTE

SINGLE_MESSAGE_BATCH_SIZE = 1
SQS_DEFAULT_BATCH_WINDOW = int(timedelta(seconds=5).total_seconds())

# TODO revisar tiempo de ejecución no exceda 15min
PROCESS_QUERY_METADATA = 100  # TODO 900s
DOWNLOAD_QUERY_BATCH_SIZE = 120
PROCESS_QUERY_XML_BATCH_SIZE = 100  # TODO 900s
SEND_QUERY_METADATA_LISTENER_BATCH_SIZE = 500
PROCESS_PAYMENTS_BATCH_SIZE = 1  # TODO 900s
VERIFY_QUERY_BATCH_SIZE = 120
UPDATER_QUERY_BATCH_SIZE = 120
ADD_DATA_SYNC_BATCH_SIZE = 150
NOTIFICATIONS_BATCH_SIZE = 100
SCRAP_PROCESS_RESULTS_BATCH_SIZE = 100  # TODO revisar
ADD_PROCESS_METADATA_BATCH_SIZE = 4
MASSIVE_EXPORT_BATCH_SIZE = 3
ADD_METADATA_REQUEST_BATCH_SIZE = 2
RESET_ADD_LICENSE_KEY_BATCH_SIZE = 3
TO_EXPORT_BATCH_SIZE = 1  # TODO 900s
SCRAP_DELAYER_BATCH_SIZE = 1
SQS_COMPLETE_CFDIS_BATCH_SIZE = 10

PROCESS_PACKAGE_XML_RDS_BUSY_DELAY_MIN = timedelta(minutes=1)
PROCESS_PACKAGE_XML_RDS_BUSY_DELAY_MAX = timedelta(minutes=5)
PROCESS_PACKAGE_XML_WARNING_LAMBDA_TIMEOUT = timedelta(minutes=10)  # TODO fine tunning
PROCESS_PACKAGE_XML_MAX_DELAY = timedelta(hours=1)  # TODO fine tunning
REVERIFY_MAX_DELAY = timedelta(
    hours=int(os.environ.get("REVERIFY_MAX_DELAY_HOURS", 5))
)  # TODO fine tunning
COMPLETE_CFDIS_MAX_DELAY = timedelta(hours=3)  # TODO fine tunning
NOTIFICATIONS_MAX_DELAY = timedelta(hours=1)  # TODO fine tunning

PROCESS_CFDI_DELAY_SECONDS = int(timedelta(minutes=5).total_seconds())

PASTO_METADATA_PROCESS_DELAY = timedelta(hours=1)

DELAYER = "delayer"
DELAYER_BATCH_SIZE = 10_000
DELAYER_BATCH_WINDOW = int(timedelta(seconds=30).total_seconds())
SYNC_METADATA_MAX_DELAY = timedelta(hours=2)
PROCESS_METADATA_MAX_DELAY = timedelta(hours=2)
