"""poliza

Revision ID: 47c8915a934c
Revises: d36bba504e9c
Create Date: 2025-09-04 11:11:37.616287

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from chalicelib.alembic_tenant.utils import resolve_schema

# revision identifiers, used by Alembic.
revision = "47c8915a934c"
down_revision = "d36bba504e9c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "poliza",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("identifier", postgresql.UUID(), nullable=False),
        sa.Column("fecha", sa.DateTime(), nullable=False),
        sa.Column("tipo", sa.String(), nullable=False),
        sa.Column("numero", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("identifier"),
        schema=resolve_schema("per_tenant"),
    )
    op.create_index(
        "ix_poliza_unique",
        "poliza",
        ["fecha", "tipo", "numero"],
        unique=True,
        schema=resolve_schema("per_tenant"),
    )
    op.create_table(
        "poliza_cfdi",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("poliza_identifier", postgresql.UUID(), nullable=False),
        sa.Column("uuid_related", postgresql.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["poliza_identifier"], ["per_tenant.poliza.identifier"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("poliza_identifier", "uuid_related"),
        schema=resolve_schema("per_tenant"),
    )


def downgrade():
    op.drop_table("poliza_cfdi", schema=resolve_schema("per_tenant"))
    op.drop_index("ix_poliza_unique", table_name="poliza", schema=resolve_schema("per_tenant"))
    op.drop_table("poliza", schema=resolve_schema("per_tenant"))
