"""attachment

Revision ID: 4ff1fc8da266
Revises: 7b5943e5176b
Create Date: 2025-12-11 11:04:13.127111

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from chalicelib.alembic_tenant.utils import resolve_schema

# revision identifiers, used by Alembic.
revision = "4ff1fc8da266"
down_revision = "7b5943e5176b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attachment",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("identifier", postgresql.UUID(), nullable=False),
        sa.Column("cfdi_uuid", postgresql.UUID(), nullable=False),
        sa.Column("creator_identifier", postgresql.UUID(), nullable=False),
        sa.Column("deleter_identifier", postgresql.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("s3_key", sa.String(), nullable=False),
        sa.Column(
            "state",
            sa.Enum("PENDING", "CONFIRMED", "DELETED", name="attachment_state"),
            nullable=False,
        ),
        # sa.ForeignKeyConstraint(
        #     ["cfdi_uuid"],
        #     ["per_tenant.cfdi.UUID"],
        #     name=op.f("fk_attachment_cfdi_uuid_cfdi"),
        #     ondelete="CASCADE",
        # ),
        # sa.ForeignKeyConstraint(
        #     ["creator_identifier"],
        #     ["user.identifier"],
        #     name=op.f("fk_attachment_creator_identifier_user"),
        #     ondelete="CASCADE",
        # ),
        # sa.ForeignKeyConstraint(
        #     ["deleter_identifier"],
        #     ["user.identifier"],
        #     name=op.f("fk_attachment_deleter_identifier_user"),
        #     ondelete="CASCADE",
        # ),
        sa.PrimaryKeyConstraint("identifier", name=op.f("attachment_pkey")),
        schema=resolve_schema("per_tenant"),
    )
    op.create_index(
        "idx_attachment_cfdi_filename_unique",
        "attachment",
        ["cfdi_uuid", "file_name"],
        unique=True,
        schema=resolve_schema("per_tenant"),
        postgresql_where=sa.text("state != 'DELETED'"),
    )
    op.create_index(
        op.f("ix_attachment_cfdi_uuid"),
        "attachment",
        ["cfdi_uuid"],
        unique=False,
        schema=resolve_schema("per_tenant"),
    )
    op.create_index(
        op.f("ix_attachment_file_name"),
        "attachment",
        ["file_name"],
        unique=False,
        schema=resolve_schema("per_tenant"),
    )
    op.create_index(
        op.f("ix_attachment_state"),
        "attachment",
        ["state"],
        unique=False,
        schema=resolve_schema("per_tenant"),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_attachment_state"), table_name="attachment", schema=resolve_schema("per_tenant")
    )
    op.drop_index(
        op.f("ix_attachment_file_name"),
        table_name="attachment",
        schema=resolve_schema("per_tenant"),
    )
    op.drop_index(
        op.f("ix_attachment_cfdi_uuid"),
        table_name="attachment",
        schema=resolve_schema("per_tenant"),
    )
    op.drop_index(
        "idx_attachment_cfdi_filename_unique",
        table_name="attachment",
        schema=resolve_schema("per_tenant"),
        postgresql_where=sa.text("state != 'DELETED'"),
    )
    op.drop_table("attachment", schema=resolve_schema("per_tenant"))
    # ### end Alembic commands ###
