"""poliza_movimiento

Revision ID: 69c62d0e5c77
Revises: c2f721a8bf58
Create Date: 2025-11-12 17:31:13.054728

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from chalicelib.alembic_tenant.utils import resolve_schema

# revision identifiers, used by Alembic.
revision = "69c62d0e5c77"
down_revision = "c2f721a8bf58"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "poliza_movimiento",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("identifier", postgresql.UUID(), nullable=False),
        sa.Column("numerador", sa.String(), nullable=True),
        sa.Column("cuenta_contable", sa.String(), nullable=True),
        sa.Column("nombre", sa.String(), nullable=True),
        sa.Column("cargo", sa.Numeric(), nullable=False),
        sa.Column("abono", sa.Numeric(), nullable=False),
        sa.Column("cargo_me", sa.Numeric(), nullable=False),
        sa.Column("abono_me", sa.Numeric(), nullable=False),
        sa.Column("concepto", sa.String(), nullable=True),
        sa.Column("referencia", sa.String(), nullable=True),
        sa.Column("poliza_identifier", postgresql.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["poliza_identifier"],
            ["per_tenant.poliza.identifier"],
            name=op.f("fk_poliza_movimiento_poliza_identifier_poliza"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("identifier", name=op.f("poliza_movimiento_pkey")),
        schema=resolve_schema("per_tenant"),
    )
    op.create_index(
        op.f("ix_poliza_movimiento_poliza_identifier"),
        "poliza_movimiento",
        ["poliza_identifier"],
        unique=False,
        schema=resolve_schema("per_tenant"),
    )

    op.add_column(
        "poliza",
        sa.Column("concepto", sa.String(), nullable=True),
        schema=resolve_schema("per_tenant"),
    )
    op.add_column(
        "poliza",
        sa.Column("sistema_origen", sa.String(), nullable=True),
        schema=resolve_schema("per_tenant"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("poliza", "sistema_origen", schema=resolve_schema("per_tenant"))
    op.drop_column("poliza", "concepto", schema=resolve_schema("per_tenant"))
    op.drop_index(
        op.f("ix_poliza_movimiento_poliza_identifier"),
        table_name="poliza_movimiento",
        schema=resolve_schema("per_tenant"),
    )
    op.drop_table("poliza_movimiento", schema=resolve_schema("per_tenant"))
    # ### end Alembic commands ###
