"""docto_excluded_isr

Revision ID: 7b5943e5176b
Revises: c2f721a8bf58
Create Date: 2025-11-04 16:47:10.698326

"""

import sqlalchemy as sa
from alembic import op

from chalicelib.alembic_tenant.utils import resolve_schema

# revision identifiers, used by Alembic.
revision = "7b5943e5176b"
down_revision = "c2f721a8bf58"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payment_relation",
        sa.Column("ExcludeFromISR", sa.Boolean(), server_default="FALSE", nullable=False),
        schema=resolve_schema("per_tenant"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payment_relation", "ExcludeFromISR", schema=resolve_schema("per_tenant"))
    # ### end Alembic commands ###
