"""UserConfig

Revision ID: cfbfc75ddf2e
Revises: dcf93bda5aaf
Create Date: 2025-06-18 10:57:12.641810

"""

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "cfbfc75ddf2e"
down_revision = "dcf93bda5aaf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    return
    # op.create_table(
    #     "user_config",
    #     sa.Column("created_at", sa.DateTime(), nullable=True),
    #     sa.Column("updated_at", sa.DateTime(), nullable=True),
    #     sa.Column("user_identifier", postgresql.UUID(), nullable=False),
    #     sa.Column("data", sa.JSON(), nullable=False),
    #     sa.PrimaryKeyConstraint("user_identifier"),
    # )
    # op.alter_column(
    #     "payment_relation", "FechaPago", existing_type=postgresql.TIMESTAMP(), nullable=False
    # )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "payment_relation", "FechaPago", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.drop_index("ix_user_config_id", table_name="user_config")
    op.drop_index("ix_user_config_user_id", table_name="user_config")
    op.drop_table("user_config")
    # ### end Alembic commands ###
