"""initial tenant schema

Revision ID: dc6b127ee1c8
Revises:
Create Date: 2025-05-23 15:17:10.178840

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from chalicelib.schema.UserDefinedType.mx_amount import MXAmount
from chalicelib.schema.UserDefinedType.xml_type import XMLType

# revision identifiers, used by Alembic.
revision = "dc6b127ee1c8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_config",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("user_identifier", postgresql.UUID(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("user_identifier"),
    )

    op.create_table(
        "add_sync_request",
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("identifier", postgresql.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("start", sa.Date(), nullable=False),
        sa.Column("end", sa.Date(), nullable=False),
        sa.Column("xmls_to_send", sa.Integer(), nullable=False),
        sa.Column("xmls_to_send_pending", sa.Integer(), nullable=False),
        sa.Column("xmls_to_send_total", sa.Float(), nullable=False),
        sa.Column("cfdis_to_cancel", sa.Integer(), nullable=False),
        sa.Column("cfdis_to_cancel_pending", sa.Integer(), nullable=False),
        sa.Column("cfdis_to_cancel_total", sa.Float(), nullable=False),
        sa.Column("pasto_sent_identifier", postgresql.UUID(), nullable=True),
        sa.Column("pasto_cancel_identifier", postgresql.UUID(), nullable=True),
        sa.Column(
            "state",
            sa.Enum("DRAFT", "SENT", "ERROR", name="enum_add_sync_request_state"),
            nullable=False,
        ),
        sa.Column("manually_triggered", sa.Boolean(), server_default="false", nullable=False),
        sa.PrimaryKeyConstraint("identifier"),
    )
    op.create_index(
        op.f("ix_add_sync_request_created_at"), "add_sync_request", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_add_sync_request_state"), "add_sync_request", ["state"], unique=False)
    op.create_table(
        "cfdi",
        sa.Column("is_issued", sa.Boolean(), nullable=False),
        sa.Column("UUID", postgresql.UUID(), nullable=False),
        sa.Column("Fecha", sa.DateTime(), nullable=False),
        sa.Column("Total", sa.Numeric(), nullable=False),
        sa.Column("Folio", sa.String(), nullable=True),
        sa.Column("Serie", sa.String(), nullable=True),
        sa.Column("NoCertificado", sa.String(), nullable=True),
        sa.Column("Certificado", sa.String(), nullable=True),
        sa.Column("TipoDeComprobante", sa.String(), nullable=False),
        sa.Column("LugarExpedicion", sa.String(), nullable=True),
        sa.Column("FormaPago", sa.String(), nullable=True),
        sa.Column("MetodoPago", sa.String(), nullable=True),
        sa.Column("Moneda", sa.String(), nullable=True),
        sa.Column("SubTotal", sa.Numeric(), nullable=True),
        sa.Column("RfcEmisor", sa.String(), nullable=False),
        sa.Column("NombreEmisor", sa.String(), nullable=True),
        sa.Column("RfcReceptor", sa.String(), nullable=False),
        sa.Column("NombreReceptor", sa.String(), nullable=True),
        sa.Column("RfcPac", sa.String(), nullable=True),
        sa.Column("FechaCertificacionSat", sa.DateTime(), nullable=False),
        sa.Column("Estatus", sa.Boolean(), nullable=False),
        sa.Column("ExcludeFromIVA", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.Column("ExcludeFromISR", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.Column("FechaCancelacion", sa.DateTime(), nullable=True),
        sa.Column("TipoCambio", sa.Numeric(), nullable=True),
        sa.Column("Conceptos", sa.String(), nullable=True),
        sa.Column("Version", sa.String(), nullable=True),
        sa.Column("Sello", sa.String(), nullable=True),
        sa.Column("UsoCFDIReceptor", sa.String(), nullable=True),
        sa.Column("RegimenFiscalEmisor", sa.String(), nullable=True),
        sa.Column("CondicionesDePago", sa.String(), nullable=True),
        sa.Column("CfdiRelacionados", sa.String(), nullable=True),
        sa.Column("Neto", sa.Numeric(), nullable=True),
        sa.Column("TrasladosIVA", sa.Numeric(), nullable=True),
        sa.Column("TrasladosIEPS", sa.Numeric(), nullable=True),
        sa.Column("TrasladosISR", sa.Numeric(), nullable=True),
        sa.Column("RetencionesIVA", sa.Numeric(), nullable=True),
        sa.Column("RetencionesIEPS", sa.Numeric(), nullable=True),
        sa.Column("RetencionesISR", sa.Numeric(), nullable=True),
        sa.Column("FechaFiltro", sa.DateTime(), nullable=False),
        sa.Column("Impuestos", sa.String(), nullable=True),
        sa.Column("Exportacion", sa.String(), nullable=True),
        sa.Column("Periodicidad", sa.String(), nullable=True),
        sa.Column("Meses", sa.String(), nullable=True),
        sa.Column("Year", sa.String(), nullable=True),
        sa.Column("DomicilioFiscalReceptor", sa.String(), nullable=True),
        sa.Column("RegimenFiscalReceptor", sa.String(), nullable=True),
        sa.Column("TotalMXN", sa.Numeric(), nullable=True),
        sa.Column("SubTotalMXN", sa.Numeric(), nullable=True),
        sa.Column("NetoMXN", sa.Numeric(), nullable=True),
        sa.Column("DescuentoMXN", sa.Numeric(), nullable=True),
        sa.Column("TrasladosIVAMXN", sa.Numeric(), nullable=True),
        sa.Column("TrasladosIEPSMXN", sa.Numeric(), nullable=True),
        sa.Column("TrasladosISRMXN", sa.Numeric(), nullable=True),
        sa.Column("RetencionesIVAMXN", sa.Numeric(), nullable=True),
        sa.Column("RetencionesIEPSMXN", sa.Numeric(), nullable=True),
        sa.Column("RetencionesISRMXN", sa.Numeric(), nullable=True),
        sa.Column("NoCertificadoSAT", sa.String(), nullable=True),
        sa.Column("SelloSAT", sa.String(), nullable=True),
        sa.Column("Descuento", sa.Numeric(), nullable=True),
        sa.Column("PaymentDate", sa.DateTime(), nullable=False),
        sa.Column("TipoDeComprobante_I_MetodoPago_PPD", sa.Boolean(), nullable=False),
        sa.Column("TipoDeComprobante_I_MetodoPago_PUE", sa.Boolean(), nullable=False),
        sa.Column("TipoDeComprobante_E_MetodoPago_PPD", sa.Boolean(), nullable=False),
        sa.Column("TipoDeComprobante_E_CfdiRelacionados_None", sa.Boolean(), nullable=False),
        sa.Column("cancelled_other_month", sa.Boolean(), nullable=False),
        sa.Column("other_rfc", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("is_too_big", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.Column("from_xml", sa.Boolean(), nullable=False),
        sa.Column("xml_content", XMLType(), nullable=True),
        sa.Column("add_exists", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.Column("add_cancel_date", sa.DateTime(), nullable=True),
        sa.Column("BaseIVA16", sa.Numeric(), nullable=True),
        sa.Column("BaseIVA8", sa.Numeric(), nullable=True),
        sa.Column("BaseIVA0", sa.Numeric(), nullable=True),
        sa.Column("BaseIVAExento", sa.Numeric(), nullable=True),
        sa.Column("IVATrasladado16", sa.Numeric(), nullable=True),
        sa.Column("IVATrasladado8", sa.Numeric(), nullable=True),
        sa.Column("pr_count", sa.Numeric(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("is_issued", "UUID"),
    )
    op.create_index(
        "cfdi_Fecha_Estatus_from_xml_is_too_big_idx",
        "cfdi",
        ["Fecha", "Estatus", "from_xml", "is_too_big"],
        unique=False,
        postgresql_where='("Estatus" AND (NOT from_xml) AND (NOT is_too_big))',
    )
    op.create_index(
        "cfdi_add_exists_UUID_add_cancel_date_idx",
        "cfdi",
        ["add_exists", "UUID", "add_cancel_date"],
        unique=False,
    )
    op.create_index("cfdi_add_exists_UUID_idx", "cfdi", ["add_exists", "UUID"], unique=False)
    op.create_index(op.f("ix_cfdi_FechaCancelacion"), "cfdi", ["FechaCancelacion"], unique=False)
    op.create_index(op.f("ix_cfdi_FechaFiltro"), "cfdi", ["FechaFiltro"], unique=False)
    op.create_index(op.f("ix_cfdi_MetodoPago"), "cfdi", ["MetodoPago"], unique=False)
    op.create_index(op.f("ix_cfdi_PaymentDate"), "cfdi", ["PaymentDate"], unique=False)
    op.create_index(op.f("ix_cfdi_TipoDeComprobante"), "cfdi", ["TipoDeComprobante"], unique=False)
    op.create_index(op.f("ix_cfdi_UUID"), "cfdi", ["UUID"], unique=False)
    op.create_index(op.f("ix_cfdi_created_at"), "cfdi", ["created_at"], unique=False)
    op.create_index(op.f("ix_cfdi_other_rfc"), "cfdi", ["other_rfc"], unique=False)
    op.create_table(
        "cfdi_export",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("identifier", postgresql.UUID(), nullable=False),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column(
            "state", sa.Enum("SENT", "TO_DOWNLOAD", "ERROR", name="cfdiexportstate"), nullable=True
        ),
        sa.Column("expiration_date", sa.DateTime(), nullable=True),
        sa.Column("start", sa.String(), nullable=True),
        sa.Column("end", sa.String(), nullable=True),
        sa.Column("cfdi_type", sa.String(), nullable=True),
        sa.Column("download_type", sa.String(), nullable=True),
        sa.Column("format", sa.String(), nullable=True),
        sa.Column("external_request", sa.Boolean(), nullable=True),
        sa.Column(
            "export_data_type",
            sa.Enum("CFDI", "IVA", "ISR", name="exportdatatype"),
            server_default="CFDI",
            nullable=True,
        ),
        sa.Column("displayed_name", sa.String(), server_default="", nullable=False),
        sa.Column("file_name", sa.String(), server_default="", nullable=False),
        sa.Column("domain", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("identifier"),
    )
    op.create_index(op.f("ix_cfdi_export_cfdi_type"), "cfdi_export", ["cfdi_type"], unique=False)
    op.create_index(
        op.f("ix_cfdi_export_displayed_name"), "cfdi_export", ["displayed_name"], unique=False
    )
    op.create_index(
        op.f("ix_cfdi_export_download_type"), "cfdi_export", ["download_type"], unique=False
    )
    op.create_index(op.f("ix_cfdi_export_end"), "cfdi_export", ["end"], unique=False)
    op.create_index(
        op.f("ix_cfdi_export_expiration_date"), "cfdi_export", ["expiration_date"], unique=False
    )
    op.create_index(
        op.f("ix_cfdi_export_export_data_type"), "cfdi_export", ["export_data_type"], unique=False
    )
    op.create_index(op.f("ix_cfdi_export_file_name"), "cfdi_export", ["file_name"], unique=False)
    op.create_index(op.f("ix_cfdi_export_format"), "cfdi_export", ["format"], unique=False)
    op.create_index(op.f("ix_cfdi_export_start"), "cfdi_export", ["start"], unique=False)
    op.create_index(op.f("ix_cfdi_export_state"), "cfdi_export", ["state"], unique=False)
    op.create_index(op.f("ix_cfdi_export_url"), "cfdi_export", ["url"], unique=False)
    op.create_table(
        "cfdi_relation",
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("identifier", postgresql.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("uuid_origin", postgresql.UUID(), nullable=False),
        sa.Column("TipoDeComprobante", sa.String(), nullable=False),
        sa.Column("is_issued", sa.Boolean(), nullable=False),
        sa.Column("Estatus", sa.Boolean(), nullable=False),
        sa.Column("uuid_related", postgresql.UUID(), nullable=False),
        sa.Column("TipoRelacion", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("identifier", "is_issued"),
    )
    op.create_index(
        op.f("ix_cfdi_relation_TipoDeComprobante"),
        "cfdi_relation",
        ["TipoDeComprobante"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cfdi_relation_created_at"), "cfdi_relation", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_cfdi_relation_uuid_origin"), "cfdi_relation", ["uuid_origin"], unique=False
    )
    op.create_index(
        op.f("ix_cfdi_relation_uuid_related"), "cfdi_relation", ["uuid_related"], unique=False
    )
    op.create_table(
        "nomina",
        sa.Column("cfdi_uuid", postgresql.UUID(), nullable=False),
        sa.Column("Version", sa.Enum("1.1", "1.2", name="enum_nomina_Version"), nullable=False),
        sa.Column("TipoNomina", sa.Enum("O", "E", name="enum_nomina_TipoNomina"), nullable=False),
        sa.Column("FechaPago", sa.DateTime(), nullable=False),
        sa.Column("FechaInicialPago", sa.DateTime(), nullable=False),
        sa.Column("FechaFinalPago", sa.DateTime(), nullable=False),
        sa.Column("NumDiasPagados", sa.Numeric(), nullable=False),
        sa.Column("TotalPercepciones", sa.Numeric(), nullable=True),
        sa.Column("TotalDeducciones", sa.Numeric(), nullable=True),
        sa.Column("TotalOtrosPagos", sa.Numeric(), nullable=True),
        sa.Column("EmisorRegistroPatronal", sa.String(), nullable=True),
        sa.Column("ReceptorCurp", sa.String(), nullable=False),
        sa.Column("ReceptorNumSeguridadSocial", sa.String(), nullable=True),
        sa.Column("ReceptorFechaInicioRelLaboral", sa.DateTime(), nullable=True),
        sa.Column("ReceptorAntigüedad", sa.String(), nullable=True),
        sa.Column(
            "ReceptorTipoContrato",
            sa.Enum(
                "01",
                "02",
                "03",
                "04",
                "05",
                "06",
                "07",
                "08",
                "09",
                "10",
                "99",
                name="enum_nomina_ReceptorTipoContrato",
            ),
            nullable=False,
        ),
        sa.Column("ReceptorSindicalizado", sa.Boolean(), nullable=True),
        sa.Column(
            "ReceptorTipoJornada",
            sa.Enum(
                "01",
                "02",
                "03",
                "04",
                "05",
                "06",
                "07",
                "08",
                "99",
                name="enum_nomina_ReceptorTipoJornada",
            ),
            nullable=True,
        ),
        sa.Column(
            "ReceptorTipoRegimen",
            sa.Enum(
                "02",
                "03",
                "04",
                "05",
                "06",
                "07",
                "08",
                "09",
                "10",
                "11",
                "12",
                "13",
                "99",
                name="enum_nomina_ReceptorTipoRegimen",
            ),
            nullable=False,
        ),
        sa.Column("ReceptorNumEmpleado", sa.String(), nullable=False),
        sa.Column("ReceptorDepartamento", sa.String(), nullable=True),
        sa.Column("ReceptorPuesto", sa.String(), nullable=True),
        sa.Column(
            "ReceptorRiesgoPuesto",
            sa.Enum("1", "2", "3", "4", "5", "99", name="enum_nomina_ReceptorRiesgoPuesto"),
            nullable=True,
        ),
        sa.Column(
            "ReceptorPeriodicidadPago",
            sa.Enum(
                "01",
                "02",
                "03",
                "04",
                "05",
                "06",
                "07",
                "08",
                "09",
                "10",
                "99",
                name="enum_nomina_ReceptorPeriodicidadPago",
            ),
            nullable=False,
        ),
        sa.Column(
            "ReceptorBanco",
            sa.Enum(
                "002",
                "006",
                "009",
                "012",
                "014",
                "019",
                "021",
                "030",
                "032",
                "036",
                "037",
                "042",
                "044",
                "058",
                "059",
                "060",
                "062",
                "072",
                "102",
                "103",
                "106",
                "108",
                "110",
                "112",
                "113",
                "116",
                "124",
                "126",
                "127",
                "128",
                "129",
                "130",
                "131",
                "132",
                "133",
                "134",
                "135",
                "136",
                "137",
                "138",
                "139",
                "140",
                "141",
                "143",
                "145",
                "147",
                "148",
                "149",
                "150",
                "151",
                "152",
                "153",
                "154",
                "155",
                "156",
                "157",
                "158",
                "159",
                "160",
                "166",
                "168",
                "600",
                "601",
                "602",
                "605",
                "606",
                "607",
                "608",
                "610",
                "614",
                "615",
                "616",
                "617",
                "618",
                "619",
                "620",
                "621",
                "622",
                "623",
                "626",
                "627",
                "628",
                "629",
                "630",
                "631",
                "632",
                "633",
                "634",
                "636",
                "637",
                "638",
                "640",
                "642",
                "646",
                "647",
                "648",
                "649",
                "651",
                "652",
                "653",
                "655",
                "656",
                "659",
                "670",
                "901",
                "902",
                name="enum_nomina_ReceptorBanco",
            ),
            nullable=True,
        ),
        sa.Column("ReceptorCuentaBancaria", sa.String(), nullable=True),
        sa.Column("ReceptorSalarioBaseCotApor", sa.Numeric(), nullable=True),
        sa.Column("ReceptorSalarioDiarioIntegrado", sa.Numeric(), nullable=True),
        sa.Column(
            "ReceptorClaveEntFed",
            sa.Enum(
                "AGU",
                "BCN",
                "BCS",
                "CAM",
                "CHP",
                "CHH",
                "COA",
                "COL",
                "CMX",
                "DIF",
                "DUR",
                "GUA",
                "GRO",
                "HID",
                "JAL",
                "MEX",
                "MIC",
                "MOR",
                "NAY",
                "NLE",
                "OAX",
                "PUE",
                "QUE",
                "ROO",
                "SLP",
                "SIN",
                "SON",
                "TAB",
                "TAM",
                "TLA",
                "VER",
                "YUC",
                "ZAC",
                "AL",
                "AK",
                "AZ",
                "AR",
                "CA",
                "NC",
                "SC",
                "CO",
                "CT",
                "ND",
                "SD",
                "DE",
                "FL",
                "GA",
                "HI",
                "ID",
                "IL",
                "IN",
                "IA",
                "KS",
                "KY",
                "LA",
                "ME",
                "MD",
                "MA",
                "MI",
                "MN",
                "MS",
                "MO",
                "MT",
                "NE",
                "NV",
                "NJ",
                "NY",
                "NH",
                "NM",
                "OH",
                "OK",
                "OR",
                "PA",
                "RI",
                "TN",
                "TX",
                "UT",
                "VT",
                "VA",
                "WV",
                "WA",
                "WI",
                "WY",
                "ON",
                "QC",
                "NS",
                "NB",
                "MB",
                "BC",
                "PE",
                "SK",
                "AB",
                "NL",
                "NT",
                "YT",
                "UN",
                name="enum_nomina_ReceptorClaveEntFed",
            ),
            nullable=False,
        ),
        sa.Column("PercepcionesTotalSueldos", sa.Numeric(), nullable=True),
        sa.Column("PercepcionesTotalGravado", sa.Numeric(), nullable=True),
        sa.Column("PercepcionesTotalExento", sa.Numeric(), nullable=True),
        sa.Column("PercepcionesSeparacionIndemnizacion", sa.Numeric(), nullable=True),
        sa.Column("PercepcionesJubilacionPensionRetiro", sa.Numeric(), nullable=True),
        sa.Column("DeduccionesTotalOtrasDeducciones", sa.Numeric(), nullable=True),
        sa.Column("DeduccionesTotalImpuestosRetenidos", sa.Numeric(), nullable=True),
        sa.Column("SubsidioCausado", sa.Numeric(), nullable=True),
        sa.Column("AjusteISRRetenido", sa.Numeric(), nullable=True),
        sa.PrimaryKeyConstraint("cfdi_uuid"),
    )
    op.create_index(
        op.f("ix_nomina_EmisorRegistroPatronal"), "nomina", ["EmisorRegistroPatronal"], unique=False
    )
    op.create_index(op.f("ix_nomina_FechaFinalPago"), "nomina", ["FechaFinalPago"], unique=False)
    op.create_index(
        op.f("ix_nomina_FechaInicialPago"), "nomina", ["FechaInicialPago"], unique=False
    )
    op.create_index(op.f("ix_nomina_FechaPago"), "nomina", ["FechaPago"], unique=False)
    op.create_index(op.f("ix_nomina_ReceptorBanco"), "nomina", ["ReceptorBanco"], unique=False)
    op.create_index(
        op.f("ix_nomina_ReceptorClaveEntFed"), "nomina", ["ReceptorClaveEntFed"], unique=False
    )
    op.create_index(op.f("ix_nomina_ReceptorCurp"), "nomina", ["ReceptorCurp"], unique=False)
    op.create_index(
        op.f("ix_nomina_ReceptorDepartamento"), "nomina", ["ReceptorDepartamento"], unique=False
    )
    op.create_index(
        op.f("ix_nomina_ReceptorNumEmpleado"), "nomina", ["ReceptorNumEmpleado"], unique=False
    )
    op.create_index(
        op.f("ix_nomina_ReceptorNumSeguridadSocial"),
        "nomina",
        ["ReceptorNumSeguridadSocial"],
        unique=False,
    )
    op.create_index(
        op.f("ix_nomina_ReceptorPeriodicidadPago"),
        "nomina",
        ["ReceptorPeriodicidadPago"],
        unique=False,
    )
    op.create_index(op.f("ix_nomina_ReceptorPuesto"), "nomina", ["ReceptorPuesto"], unique=False)
    op.create_index(
        op.f("ix_nomina_ReceptorRiesgoPuesto"), "nomina", ["ReceptorRiesgoPuesto"], unique=False
    )
    op.create_index(
        op.f("ix_nomina_ReceptorTipoContrato"), "nomina", ["ReceptorTipoContrato"], unique=False
    )
    op.create_index(
        op.f("ix_nomina_ReceptorTipoJornada"), "nomina", ["ReceptorTipoJornada"], unique=False
    )
    op.create_index(
        op.f("ix_nomina_ReceptorTipoRegimen"), "nomina", ["ReceptorTipoRegimen"], unique=False
    )
    op.create_index(op.f("ix_nomina_TipoNomina"), "nomina", ["TipoNomina"], unique=False)
    op.create_index(op.f("ix_nomina_Version"), "nomina", ["Version"], unique=False)
    op.create_index(op.f("ix_nomina_cfdi_uuid"), "nomina", ["cfdi_uuid"], unique=False)
    op.create_table(
        "payment",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("identifier", postgresql.UUID(), nullable=False),
        sa.Column("is_issued", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("uuid_origin", postgresql.UUID(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("FechaPago", sa.DateTime(), nullable=False),
        sa.Column("FormaDePagoP", sa.String(), nullable=False),
        sa.Column("MonedaP", sa.String(), nullable=False),
        sa.Column("Monto", sa.Numeric(), nullable=False),
        sa.Column("TipoCambioP", sa.Numeric(), nullable=True),
        sa.Column("NumOperacion", sa.String(), nullable=True),
        sa.Column("RfcEmisorCtaOrd", sa.String(), nullable=True),
        sa.Column("NomBancoOrdExt", sa.String(), nullable=True),
        sa.Column("CtaOrdenante", sa.String(), nullable=True),
        sa.Column("RfcEmisorCtaBen", sa.String(), nullable=True),
        sa.Column("CtaBeneficiario", sa.String(), nullable=True),
        sa.Column("TipoCadPago", sa.String(), nullable=True),
        sa.Column("CertPago", sa.String(), nullable=True),
        sa.Column("CadPago", sa.String(), nullable=True),
        sa.Column("SelloPago", sa.String(), nullable=True),
        sa.Column("Estatus", sa.Boolean(), server_default="TRUE", nullable=False),
        sa.PrimaryKeyConstraint("identifier"),
    )
    op.create_index(op.f("ix_payment_index"), "payment", ["index"], unique=False)
    op.create_index(op.f("ix_payment_uuid_origin"), "payment", ["uuid_origin"], unique=False)
    op.create_table(
        "payment_relation",
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("identifier", postgresql.UUID(), nullable=False),
        sa.Column("is_issued", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("payment_identifier", postgresql.UUID(), nullable=False),
        sa.Column("UUID", postgresql.UUID(), nullable=False),
        sa.Column("UUID_related", postgresql.UUID(), nullable=False),
        sa.Column("FechaPago", sa.DateTime(), nullable=False),
        sa.Column("Serie", sa.String(), nullable=True),
        sa.Column("Folio", sa.String(), nullable=True),
        sa.Column("MonedaDR", sa.String(), nullable=False),
        sa.Column("EquivalenciaDR", sa.Numeric(), nullable=True),
        sa.Column("MetodoDePagoDR", sa.String(), nullable=True),
        sa.Column("NumParcialidad", sa.Integer(), nullable=False),
        sa.Column("ImpSaldoAnt", sa.Numeric(), nullable=False),
        sa.Column("ImpPagado", sa.Numeric(), nullable=False),
        sa.Column("ImpPagadoMXN", MXAmount(), nullable=False),
        sa.Column("ImpSaldoInsoluto", sa.Numeric(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("applied", sa.Boolean(), nullable=False),
        sa.Column("ObjetoImpDR", sa.String(), nullable=True),
        sa.Column("BaseIVA16", MXAmount(), nullable=False),
        sa.Column("BaseIVA8", MXAmount(), nullable=False),
        sa.Column("BaseIVA0", MXAmount(), nullable=False),
        sa.Column("BaseIVAExento", MXAmount(), nullable=False),
        sa.Column("IVATrasladado16", MXAmount(), nullable=False),
        sa.Column("IVATrasladado8", MXAmount(), nullable=False),
        sa.Column("TrasladosIVAMXN", MXAmount(), nullable=False),
        sa.Column(
            "RetencionesIVAMXN",
            MXAmount(),
            nullable=True,
        ),
        sa.Column("RetencionesDR", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("TrasladosDR", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("Estatus", sa.Boolean(), server_default="TRUE", nullable=False),
        sa.Column("ExcludeFromIVA", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.PrimaryKeyConstraint("identifier"),
    )
    op.create_index(op.f("ix_payment_relation_UUID"), "payment_relation", ["UUID"], unique=False)
    op.create_index(
        op.f("ix_payment_relation_UUID_related"), "payment_relation", ["UUID_related"], unique=False
    )
    op.create_index(
        op.f("ix_payment_relation_created_at"), "payment_relation", ["created_at"], unique=False
    )
    op.create_index(
        "payment_relation_company_identifier_is_issued_fecha_pago_index",
        "payment_relation",
        ["is_issued", "FechaPago"],
        unique=False,
    )
    op.create_table(
        "sat_query",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("identifier", postgresql.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("start", sa.DateTime(), nullable=False),
        sa.Column("end", sa.DateTime(), nullable=False),
        sa.Column(
            "download_type",
            sa.Enum("ISSUED", "RECEIVED", "BOTH", name="enum_sat_query_download_type"),
            nullable=False,
        ),
        sa.Column(
            "request_type",
            sa.Enum("CFDI", "METADATA", "BOTH", name="enum_sat_query_request_type"),
            nullable=False,
        ),
        sa.Column("packages", sa.JSON(), nullable=True),
        sa.Column("cfdis_qty", sa.Integer(), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "DRAFT",
                "SENT",
                "TO_DOWNLOAD",
                "DOWNLOADED",
                "TO_SCRAP",
                "DELAYED",
                "PROCESSING",
                "ERROR_IN_CERTS",
                "ERROR_SAT_WS_UNKNOWN",
                "ERROR_SAT_WS_INTERNAL",
                "ERROR_TOO_BIG",
                "TIME_LIMIT_REACHED",
                "ERROR",
                "SCRAP_FAILED",
                "CANT_SCRAP",
                "MANUALLY_CANCELLED",
                "SPLITTED",
                "INFORMATION_NOT_FOUND",
                "SUBSTITUTED",
                "SUBSTITUTED_TO_SCRAP",
                "PROCESSED",
                "SCRAPPED",
                name="enum_sat_query_state",
            ),
            nullable=False,
        ),
        sa.Column("sent_date", sa.DateTime(), nullable=True),
        sa.Column("is_manual", sa.Boolean(), server_default="FALSE", nullable=True),
        sa.Column(
            "technology",
            sa.Enum("WebService", "Scraper", name="enum_sat_query_technology"),
            server_default="WebService",
            nullable=False,
        ),
        sa.Column("origin_identifier", postgresql.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["origin_identifier"], ["sat_query.identifier"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("identifier"),
    )
    op.create_index(
        op.f("ix_sat_query_download_type"), "sat_query", ["download_type"], unique=False
    )
    op.create_index(op.f("ix_sat_query_end"), "sat_query", ["end"], unique=False)
    op.create_index(op.f("ix_sat_query_name"), "sat_query", ["name"], unique=False)
    op.create_index(op.f("ix_sat_query_request_type"), "sat_query", ["request_type"], unique=False)
    op.create_index(op.f("ix_sat_query_sent_date"), "sat_query", ["sent_date"], unique=False)
    op.create_index(op.f("ix_sat_query_start"), "sat_query", ["start"], unique=False)
    op.create_index(op.f("ix_sat_query_state"), "sat_query", ["state"], unique=False)
    op.create_index(op.f("ix_sat_query_technology"), "sat_query", ["technology"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sat_query_technology"), table_name="sat_query")
    op.drop_index(op.f("ix_sat_query_state"), table_name="sat_query")
    op.drop_index(op.f("ix_sat_query_start"), table_name="sat_query")
    op.drop_index(op.f("ix_sat_query_sent_date"), table_name="sat_query")
    op.drop_index(op.f("ix_sat_query_request_type"), table_name="sat_query")
    op.drop_index(op.f("ix_sat_query_name"), table_name="sat_query")
    op.drop_index(op.f("ix_sat_query_end"), table_name="sat_query")
    op.drop_index(op.f("ix_sat_query_download_type"), table_name="sat_query")
    op.drop_table("sat_query")
    op.drop_index(
        "payment_relation_company_identifier_is_issued_fecha_pago_index",
        table_name="payment_relation",
    )
    op.drop_index(op.f("ix_payment_relation_created_at"), table_name="payment_relation")
    op.drop_index(op.f("ix_payment_relation_UUID_related"), table_name="payment_relation")
    op.drop_index(op.f("ix_payment_relation_UUID"), table_name="payment_relation")
    op.drop_table("payment_relation")
    op.drop_index(op.f("ix_payment_uuid_origin"), table_name="payment")
    op.drop_index(op.f("ix_payment_index"), table_name="payment")
    op.drop_table("payment")
    op.drop_index(op.f("ix_nomina_cfdi_uuid"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_Version"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_TipoNomina"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_ReceptorTipoRegimen"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_ReceptorTipoJornada"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_ReceptorTipoContrato"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_ReceptorRiesgoPuesto"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_ReceptorPuesto"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_ReceptorPeriodicidadPago"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_ReceptorNumSeguridadSocial"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_ReceptorNumEmpleado"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_ReceptorDepartamento"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_ReceptorCurp"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_ReceptorClaveEntFed"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_ReceptorBanco"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_FechaPago"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_FechaInicialPago"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_FechaFinalPago"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_EmisorRegistroPatronal"), table_name="nomina")
    op.drop_table("nomina")
    op.drop_index(op.f("ix_cfdi_relation_uuid_related"), table_name="cfdi_relation")
    op.drop_index(op.f("ix_cfdi_relation_uuid_origin"), table_name="cfdi_relation")
    op.drop_index(op.f("ix_cfdi_relation_created_at"), table_name="cfdi_relation")
    op.drop_index(op.f("ix_cfdi_relation_TipoDeComprobante"), table_name="cfdi_relation")
    op.drop_table("cfdi_relation")
    op.drop_index(op.f("ix_cfdi_export_url"), table_name="cfdi_export")
    op.drop_index(op.f("ix_cfdi_export_state"), table_name="cfdi_export")
    op.drop_index(op.f("ix_cfdi_export_start"), table_name="cfdi_export")
    op.drop_index(op.f("ix_cfdi_export_format"), table_name="cfdi_export")
    op.drop_index(op.f("ix_cfdi_export_file_name"), table_name="cfdi_export")
    op.drop_index(op.f("ix_cfdi_export_export_data_type"), table_name="cfdi_export")
    op.drop_index(op.f("ix_cfdi_export_expiration_date"), table_name="cfdi_export")
    op.drop_index(op.f("ix_cfdi_export_end"), table_name="cfdi_export")
    op.drop_index(op.f("ix_cfdi_export_download_type"), table_name="cfdi_export")
    op.drop_index(op.f("ix_cfdi_export_displayed_name"), table_name="cfdi_export")
    op.drop_index(op.f("ix_cfdi_export_cfdi_type"), table_name="cfdi_export")
    op.drop_table("cfdi_export")
    op.drop_index(op.f("ix_cfdi_other_rfc"), table_name="cfdi")
    op.drop_index(op.f("ix_cfdi_created_at"), table_name="cfdi")
    op.drop_index(op.f("ix_cfdi_UUID"), table_name="cfdi")
    op.drop_index(op.f("ix_cfdi_TipoDeComprobante"), table_name="cfdi")
    op.drop_index(op.f("ix_cfdi_PaymentDate"), table_name="cfdi")
    op.drop_index(op.f("ix_cfdi_MetodoPago"), table_name="cfdi")
    op.drop_index(op.f("ix_cfdi_FechaFiltro"), table_name="cfdi")
    op.drop_index(op.f("ix_cfdi_FechaCancelacion"), table_name="cfdi")
    op.drop_index("cfdi_add_exists_UUID_idx", table_name="cfdi")
    op.drop_index("cfdi_add_exists_UUID_add_cancel_date_idx", table_name="cfdi")
    op.drop_index(
        "cfdi_Fecha_Estatus_from_xml_is_too_big_idx",
        table_name="cfdi",
        postgresql_where='("Estatus" AND (NOT from_xml) AND (NOT is_too_big))',
    )
    op.drop_table("cfdi")
    op.drop_index(op.f("ix_add_sync_request_state"), table_name="add_sync_request")
    op.drop_index(op.f("ix_add_sync_request_created_at"), table_name="add_sync_request")
    op.drop_table("add_sync_request")
    # ### end Alembic commands ###
