"""feat(add): metadata indexes

Revision ID: 02dc21533692
Revises: 9d45fb2ace37
Create Date: 2024-04-03 11:37:16.096131

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "02dc21533692"
down_revision = "9d45fb2ace37"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "cfdi_add_exists_UUID_add_cancel_date_idx",
        "cfdi",
        ["add_exists", "UUID", "add_cancel_date"],
        unique=False,
    )
    op.create_index("cfdi_add_exists_UUID_idx", "cfdi", ["add_exists", "UUID"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("cfdi_add_exists_UUID_idx", table_name="cfdi")
    op.drop_index("cfdi_add_exists_UUID_add_cancel_date_idx", table_name="cfdi")
    # ### end Alembic commands ###
