"""[ADD] CFDI.ExcludeFromISR

Revision ID: 203b4298d1e3
Revises: 7d2222d8e845
Create Date: 2023-10-11 12:09:31.213526

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "203b4298d1e3"
down_revision = "7d2222d8e845"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cfdi", sa.Column("ExcludeFromISR", sa.Boolean(), server_default="FALSE", nullable=False)
    )  # noqa E501
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cfdi", "ExcludeFromISR")
    # ### end Alembic commands ###
