"""[ADD] has_errors index

Revision ID: 26fbc55e9a11
Revises: d7e574841ff5
Create Date: 2023-11-07 11:04:53.130849

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "26fbc55e9a11"
down_revision = "d7e574841ff5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''CREATE INDEX ix_cfdi_has_errors
        ON cfdi((1)) WHERE
        "TipoDeComprobante_I_MetodoPago_PPD"
        OR "TipoDeComprobante_I_MetodoPago_PUE"
        OR "TipoDeComprobante_E_MetodoPago_PPD"
        OR "TipoDeComprobante_E_CfdiRelacionados_None"'''
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_cfdi_has_errors", table_name="cfdi")
    # ### end Alembic commands ###
