"""Remove unused models

Revision ID: 27ea151ac425
Revises: 7ef244e7f1b6
Create Date: 2025-06-18 11:51:54.899977

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "27ea151ac425"
down_revision = "7ef244e7f1b6"
branch_labels = None
depends_on = None


def upgrade():
    return  # TODO restructuracion
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_scrap_result_download_type", table_name="scrap_result")
    op.drop_index("ix_scrap_result_end_date", table_name="scrap_result")
    op.drop_index("ix_scrap_result_identifier", table_name="scrap_result")
    op.drop_index("ix_scrap_result_request_type", table_name="scrap_result")
    op.drop_index("ix_scrap_result_rfc", table_name="scrap_result")
    op.drop_index("ix_scrap_result_start_date", table_name="scrap_result")
    op.drop_table("scrap_result")
    op.drop_index("ix_currency_identifier", table_name="currency")
    op.drop_index("ix_currency_name", table_name="currency")
    op.drop_index("ix_currency_symbol", table_name="currency")
    op.drop_table("currency")
    # ### end Alembic commands ###


def downgrade():
    return  # TODO restructuracion
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currency",
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("identifier", postgresql.UUID(), autoincrement=False, nullable=True),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("symbol", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="currency_pkey"),
    )
    op.create_index("ix_currency_symbol", "currency", ["symbol"], unique=False)
    op.create_index("ix_currency_name", "currency", ["name"], unique=False)
    op.create_index("ix_currency_identifier", "currency", ["identifier"], unique=True)
    op.create_table(
        "scrap_result",
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("identifier", postgresql.UUID(), autoincrement=False, nullable=True),
        sa.Column("rfc", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("start_date", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("end_date", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("download_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("request_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("url", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="scrap_result_pkey"),
    )
    op.create_index("ix_scrap_result_start_date", "scrap_result", ["start_date"], unique=False)
    op.create_index("ix_scrap_result_rfc", "scrap_result", ["rfc"], unique=False)
    op.create_index("ix_scrap_result_request_type", "scrap_result", ["request_type"], unique=False)
    op.create_index("ix_scrap_result_identifier", "scrap_result", ["identifier"], unique=True)
    op.create_index("ix_scrap_result_end_date", "scrap_result", ["end_date"], unique=False)
    op.create_index(
        "ix_scrap_result_download_type", "scrap_result", ["download_type"], unique=False
    )
    # ### end Alembic commands ###
