"""feat(payment): all taxes in jsonb

Revision ID: 2dcc80f016fc
Revises: 4b5fc921c5dd
Create Date: 2024-10-03 16:53:46.666227

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2dcc80f016fc"
down_revision = "4b5fc921c5dd"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        "payment_relation",
        sa.Column("RetencionesDR", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "payment_relation",
        sa.Column("TrasladosDR", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payment_relation", "TrasladosDR")
    op.drop_column("payment_relation", "RetencionesDR")
