"""elimina modelos tenant

Revision ID: 48f013d43b55
Revises: e5e19c4bf6bf
Create Date: 2025-05-23 12:55:26.101883

"""

# revision identifiers, used by Alembic.
revision = "48f013d43b55"
down_revision = "e5e19c4bf6bf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
