"""[REBOOT]

Revision ID: 4c068081049f
Revises:
Create Date: 2023-09-19 16:33:31.604896

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from chalicelib.schema.UserDefinedType.xml_type import XMLType

# revision identifiers, used by Alembic.
revision = "4c068081049f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cat_aduana",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", postgresql.UUID(), nullable=True),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cat_aduana_code"), "cat_aduana", ["code"], unique=True)
    op.create_index(op.f("ix_cat_aduana_identifier"), "cat_aduana", ["identifier"], unique=False)
    op.create_index(op.f("ix_cat_aduana_name"), "cat_aduana", ["name"], unique=False)
    op.create_table(
        "cat_clave_prod_serv",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", postgresql.UUID(), nullable=True),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cat_clave_prod_serv_code"), "cat_clave_prod_serv", ["code"], unique=True
    )
    op.create_index(
        op.f("ix_cat_clave_prod_serv_identifier"),
        "cat_clave_prod_serv",
        ["identifier"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cat_clave_prod_serv_name"), "cat_clave_prod_serv", ["name"], unique=False
    )
    op.create_table(
        "cat_clave_unidad",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", postgresql.UUID(), nullable=True),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cat_clave_unidad_code"), "cat_clave_unidad", ["code"], unique=True)
    op.create_index(
        op.f("ix_cat_clave_unidad_identifier"), "cat_clave_unidad", ["identifier"], unique=False
    )
    op.create_index(op.f("ix_cat_clave_unidad_name"), "cat_clave_unidad", ["name"], unique=False)
    op.create_table(
        "cat_exportacion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", postgresql.UUID(), nullable=True),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cat_exportacion_code"), "cat_exportacion", ["code"], unique=True)
    op.create_index(
        op.f("ix_cat_exportacion_identifier"), "cat_exportacion", ["identifier"], unique=False
    )
    op.create_index(op.f("ix_cat_exportacion_name"), "cat_exportacion", ["name"], unique=False)
    op.create_table(
        "cat_forma_pago",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", postgresql.UUID(), nullable=True),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cat_forma_pago_code"), "cat_forma_pago", ["code"], unique=True)
    op.create_index(
        op.f("ix_cat_forma_pago_identifier"), "cat_forma_pago", ["identifier"], unique=False
    )
    op.create_index(op.f("ix_cat_forma_pago_name"), "cat_forma_pago", ["name"], unique=False)
    op.create_table(
        "cat_impuesto",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", postgresql.UUID(), nullable=True),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cat_impuesto_code"), "cat_impuesto", ["code"], unique=True)
    op.create_index(
        op.f("ix_cat_impuesto_identifier"), "cat_impuesto", ["identifier"], unique=False
    )
    op.create_index(op.f("ix_cat_impuesto_name"), "cat_impuesto", ["name"], unique=False)
    op.create_table(
        "cat_meses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", postgresql.UUID(), nullable=True),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cat_meses_code"), "cat_meses", ["code"], unique=True)
    op.create_index(op.f("ix_cat_meses_identifier"), "cat_meses", ["identifier"], unique=False)
    op.create_index(op.f("ix_cat_meses_name"), "cat_meses", ["name"], unique=False)
    op.create_table(
        "cat_metodo_pago",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", postgresql.UUID(), nullable=True),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cat_metodo_pago_code"), "cat_metodo_pago", ["code"], unique=True)
    op.create_index(
        op.f("ix_cat_metodo_pago_identifier"), "cat_metodo_pago", ["identifier"], unique=False
    )
    op.create_index(op.f("ix_cat_metodo_pago_name"), "cat_metodo_pago", ["name"], unique=False)
    op.create_table(
        "cat_moneda",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", postgresql.UUID(), nullable=True),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cat_moneda_code"), "cat_moneda", ["code"], unique=True)
    op.create_index(op.f("ix_cat_moneda_identifier"), "cat_moneda", ["identifier"], unique=False)
    op.create_index(op.f("ix_cat_moneda_name"), "cat_moneda", ["name"], unique=False)
    op.create_table(
        "cat_nom_banco",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_index(op.f("ix_cat_nom_banco_code"), "cat_nom_banco", ["code"], unique=False)
    op.create_index(op.f("ix_cat_nom_banco_name"), "cat_nom_banco", ["name"], unique=False)
    op.create_table(
        "cat_nom_clave_ent_fed",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_index(
        op.f("ix_cat_nom_clave_ent_fed_code"), "cat_nom_clave_ent_fed", ["code"], unique=False
    )
    op.create_index(
        op.f("ix_cat_nom_clave_ent_fed_name"), "cat_nom_clave_ent_fed", ["name"], unique=False
    )
    op.create_table(
        "cat_nom_periodicidad_pago",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_index(
        op.f("ix_cat_nom_periodicidad_pago_code"),
        "cat_nom_periodicidad_pago",
        ["code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cat_nom_periodicidad_pago_name"),
        "cat_nom_periodicidad_pago",
        ["name"],
        unique=False,
    )
    op.create_table(
        "cat_nom_riesgo_puesto",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_index(
        op.f("ix_cat_nom_riesgo_puesto_code"), "cat_nom_riesgo_puesto", ["code"], unique=False
    )
    op.create_index(
        op.f("ix_cat_nom_riesgo_puesto_name"), "cat_nom_riesgo_puesto", ["name"], unique=False
    )
    op.create_table(
        "cat_nom_tipo_contrato",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_index(
        op.f("ix_cat_nom_tipo_contrato_code"), "cat_nom_tipo_contrato", ["code"], unique=False
    )
    op.create_index(
        op.f("ix_cat_nom_tipo_contrato_name"), "cat_nom_tipo_contrato", ["name"], unique=False
    )
    op.create_table(
        "cat_nom_tipo_jornada",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_index(
        op.f("ix_cat_nom_tipo_jornada_code"), "cat_nom_tipo_jornada", ["code"], unique=False
    )
    op.create_index(
        op.f("ix_cat_nom_tipo_jornada_name"), "cat_nom_tipo_jornada", ["name"], unique=False
    )
    op.create_table(
        "cat_nom_tipo_nomina",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_index(
        op.f("ix_cat_nom_tipo_nomina_code"), "cat_nom_tipo_nomina", ["code"], unique=False
    )
    op.create_index(
        op.f("ix_cat_nom_tipo_nomina_name"), "cat_nom_tipo_nomina", ["name"], unique=False
    )
    op.create_table(
        "cat_nom_tipo_regimen",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_index(
        op.f("ix_cat_nom_tipo_regimen_code"), "cat_nom_tipo_regimen", ["code"], unique=False
    )
    op.create_index(
        op.f("ix_cat_nom_tipo_regimen_name"), "cat_nom_tipo_regimen", ["name"], unique=False
    )
    op.create_table(
        "cat_objeto_imp",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", postgresql.UUID(), nullable=True),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cat_objeto_imp_code"), "cat_objeto_imp", ["code"], unique=True)
    op.create_index(
        op.f("ix_cat_objeto_imp_identifier"), "cat_objeto_imp", ["identifier"], unique=False
    )
    op.create_index(op.f("ix_cat_objeto_imp_name"), "cat_objeto_imp", ["name"], unique=False)
    op.create_table(
        "cat_pais",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", postgresql.UUID(), nullable=True),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cat_pais_code"), "cat_pais", ["code"], unique=True)
    op.create_index(op.f("ix_cat_pais_identifier"), "cat_pais", ["identifier"], unique=False)
    op.create_index(op.f("ix_cat_pais_name"), "cat_pais", ["name"], unique=False)
    op.create_table(
        "cat_periodicidad",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", postgresql.UUID(), nullable=True),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cat_periodicidad_code"), "cat_periodicidad", ["code"], unique=True)
    op.create_index(
        op.f("ix_cat_periodicidad_identifier"), "cat_periodicidad", ["identifier"], unique=False
    )
    op.create_index(op.f("ix_cat_periodicidad_name"), "cat_periodicidad", ["name"], unique=False)
    op.create_table(
        "cat_regimen_fiscal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", postgresql.UUID(), nullable=True),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cat_regimen_fiscal_code"), "cat_regimen_fiscal", ["code"], unique=True)
    op.create_index(
        op.f("ix_cat_regimen_fiscal_identifier"), "cat_regimen_fiscal", ["identifier"], unique=False
    )
    op.create_index(
        op.f("ix_cat_regimen_fiscal_name"), "cat_regimen_fiscal", ["name"], unique=False
    )
    op.create_table(
        "cat_tipo_de_comprobante",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", postgresql.UUID(), nullable=True),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cat_tipo_de_comprobante_code"), "cat_tipo_de_comprobante", ["code"], unique=True
    )
    op.create_index(
        op.f("ix_cat_tipo_de_comprobante_identifier"),
        "cat_tipo_de_comprobante",
        ["identifier"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cat_tipo_de_comprobante_name"), "cat_tipo_de_comprobante", ["name"], unique=False
    )
    op.create_table(
        "cat_tipo_relacion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", postgresql.UUID(), nullable=True),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cat_tipo_relacion_code"), "cat_tipo_relacion", ["code"], unique=True)
    op.create_index(
        op.f("ix_cat_tipo_relacion_identifier"), "cat_tipo_relacion", ["identifier"], unique=False
    )
    op.create_index(op.f("ix_cat_tipo_relacion_name"), "cat_tipo_relacion", ["name"], unique=False)
    op.create_table(
        "cat_uso_cfdi",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", postgresql.UUID(), nullable=True),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cat_uso_cfdi_code"), "cat_uso_cfdi", ["code"], unique=True)
    op.create_index(
        op.f("ix_cat_uso_cfdi_identifier"), "cat_uso_cfdi", ["identifier"], unique=False
    )
    op.create_index(op.f("ix_cat_uso_cfdi_name"), "cat_uso_cfdi", ["name"], unique=False)
    op.create_table(
        "currency",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", postgresql.UUID(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_currency_identifier"), "currency", ["identifier"], unique=True)
    op.create_index(op.f("ix_currency_name"), "currency", ["name"], unique=False)
    op.create_index(op.f("ix_currency_symbol"), "currency", ["symbol"], unique=False)
    op.create_table(
        "efos",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", postgresql.UUID(), nullable=True),
        sa.Column("no", sa.Integer(), nullable=False),
        sa.Column("rfc", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "state",
            sa.Enum("DEFINITIVE", "DISTORTED", "ALLEGED", "FAVORABLE_JUDGMENT", name="stateenum"),
            nullable=False,
        ),
        sa.Column("sat_office_alleged", sa.String(), nullable=True),
        sa.Column("sat_publish_alleged_date", sa.String(), nullable=True),
        sa.Column("dof_office_alleged", sa.String(), nullable=True),
        sa.Column("dof_publish_alleged_date", sa.String(), nullable=True),
        sa.Column("sat_office_distored", sa.String(), nullable=True),
        sa.Column("sat_publish_distored_date", sa.String(), nullable=True),
        sa.Column("dof_office_distored", sa.String(), nullable=True),
        sa.Column("dof_publish_distored_date", sa.String(), nullable=True),
        sa.Column("sat_office_definitive", sa.String(), nullable=True),
        sa.Column("sat_publish_definitive_date", sa.String(), nullable=True),
        sa.Column("dof_office_definitive", sa.String(), nullable=True),
        sa.Column("dof_publish_definitive_date", sa.String(), nullable=True),
        sa.Column("sat_office_favorable_judgement", sa.String(), nullable=True),
        sa.Column("sat_publish_favorable_judgement_date", sa.String(), nullable=True),
        sa.Column("dof_office_favorable_judgement", sa.String(), nullable=True),
        sa.Column("dof_publish_favorable_judgement_date", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_efos_identifier"), "efos", ["identifier"], unique=True)
    op.create_index(op.f("ix_efos_name"), "efos", ["name"], unique=False)
    op.create_index(op.f("ix_efos_no"), "efos", ["no"], unique=False)
    op.create_index(op.f("ix_efos_rfc"), "efos", ["rfc"], unique=False)
    op.create_index(op.f("ix_efos_state"), "efos", ["state"], unique=False)
    op.create_table(
        "nomina",
        sa.Column("cfdi_uuid", postgresql.UUID(), nullable=False),
        sa.Column("Version", sa.Enum("1.1", "1.2", name="enum_nomina_Version"), nullable=False),
        sa.Column("TipoNomina", sa.Enum("O", "E", name="enum_nomina_TipoNomina"), nullable=False),
        sa.Column("FechaPago", sa.DateTime(), nullable=False),
        sa.Column("FechaInicialPago", sa.DateTime(), nullable=False),
        sa.Column("FechaFinalPago", sa.DateTime(), nullable=False),
        sa.Column("NumDiasPagados", sa.Numeric(), nullable=False),
        sa.Column("TotalPercepciones", sa.Numeric(), nullable=True),
        sa.Column("TotalDeducciones", sa.Numeric(), nullable=True),
        sa.Column("TotalOtrosPagos", sa.Numeric(), nullable=True),
        sa.Column("EmisorRegistroPatronal", sa.String(), nullable=True),
        sa.Column("ReceptorCurp", sa.String(), nullable=False),
        sa.Column("ReceptorNumSeguridadSocial", sa.String(), nullable=True),
        sa.Column("ReceptorFechaInicioRelLaboral", sa.DateTime(), nullable=True),
        sa.Column("ReceptorAntigüedad", sa.String(), nullable=True),
        sa.Column(
            "ReceptorTipoContrato",
            sa.Enum(
                "01",
                "02",
                "03",
                "04",
                "05",
                "06",
                "07",
                "08",
                "09",
                "10",
                "99",
                name="enum_nomina_ReceptorTipoContrato",
            ),
            nullable=False,
        ),
        sa.Column("ReceptorSindicalizado", sa.Boolean(), nullable=True),
        sa.Column(
            "ReceptorTipoJornada",
            sa.Enum(
                "01",
                "02",
                "03",
                "04",
                "05",
                "06",
                "07",
                "08",
                "99",
                name="enum_nomina_ReceptorTipoJornada",
            ),
            nullable=True,
        ),
        sa.Column(
            "ReceptorTipoRegimen",
            sa.Enum(
                "02",
                "03",
                "04",
                "05",
                "06",
                "07",
                "08",
                "09",
                "10",
                "11",
                "12",
                "13",
                "99",
                name="enum_nomina_ReceptorTipoRegimen",
            ),
            nullable=False,
        ),
        sa.Column("ReceptorNumEmpleado", sa.String(), nullable=False),
        sa.Column("ReceptorDepartamento", sa.String(), nullable=True),
        sa.Column("ReceptorPuesto", sa.String(), nullable=True),
        sa.Column(
            "ReceptorRiesgoPuesto",
            sa.Enum("1", "2", "3", "4", "5", "99", name="enum_nomina_ReceptorRiesgoPuesto"),
            nullable=True,
        ),
        sa.Column(
            "ReceptorPeriodicidadPago",
            sa.Enum(
                "01",
                "02",
                "03",
                "04",
                "05",
                "06",
                "07",
                "08",
                "09",
                "10",
                "99",
                name="enum_nomina_ReceptorPeriodicidadPago",
            ),
            nullable=False,
        ),
        sa.Column(
            "ReceptorBanco",
            sa.Enum(
                "002",
                "006",
                "009",
                "012",
                "014",
                "019",
                "021",
                "030",
                "032",
                "036",
                "037",
                "042",
                "044",
                "058",
                "059",
                "060",
                "062",
                "072",
                "102",
                "103",
                "106",
                "108",
                "110",
                "112",
                "113",
                "116",
                "124",
                "126",
                "127",
                "128",
                "129",
                "130",
                "131",
                "132",
                "133",
                "134",
                "135",
                "136",
                "137",
                "138",
                "139",
                "140",
                "141",
                "143",
                "145",
                "147",
                "148",
                "149",
                "150",
                "151",
                "152",
                "153",
                "154",
                "155",
                "156",
                "157",
                "158",
                "159",
                "160",
                "166",
                "168",
                "600",
                "601",
                "602",
                "605",
                "606",
                "607",
                "608",
                "610",
                "614",
                "615",
                "616",
                "617",
                "618",
                "619",
                "620",
                "621",
                "622",
                "623",
                "626",
                "627",
                "628",
                "629",
                "630",
                "631",
                "632",
                "633",
                "634",
                "636",
                "637",
                "638",
                "640",
                "642",
                "646",
                "647",
                "648",
                "649",
                "651",
                "652",
                "653",
                "655",
                "656",
                "659",
                "670",
                "901",
                "902",
                name="enum_nomina_ReceptorBanco",
            ),
            nullable=True,
        ),
        sa.Column("ReceptorCuentaBancaria", sa.String(), nullable=True),
        sa.Column("ReceptorSalarioBaseCotApor", sa.Numeric(), nullable=True),
        sa.Column("ReceptorSalarioDiarioIntegrado", sa.Numeric(), nullable=True),
        sa.Column(
            "ReceptorClaveEntFed",
            sa.Enum(
                "AGU",
                "BCN",
                "BCS",
                "CAM",
                "CHP",
                "CHH",
                "COA",
                "COL",
                "CMX",
                "DIF",
                "DUR",
                "GUA",
                "GRO",
                "HID",
                "JAL",
                "MEX",
                "MIC",
                "MOR",
                "NAY",
                "NLE",
                "OAX",
                "PUE",
                "QUE",
                "ROO",
                "SLP",
                "SIN",
                "SON",
                "TAB",
                "TAM",
                "TLA",
                "VER",
                "YUC",
                "ZAC",
                "AL",
                "AK",
                "AZ",
                "AR",
                "CA",
                "NC",
                "SC",
                "CO",
                "CT",
                "ND",
                "SD",
                "DE",
                "FL",
                "GA",
                "HI",
                "ID",
                "IL",
                "IN",
                "IA",
                "KS",
                "KY",
                "LA",
                "ME",
                "MD",
                "MA",
                "MI",
                "MN",
                "MS",
                "MO",
                "MT",
                "NE",
                "NV",
                "NJ",
                "NY",
                "NH",
                "NM",
                "OH",
                "OK",
                "OR",
                "PA",
                "RI",
                "TN",
                "TX",
                "UT",
                "VT",
                "VA",
                "WV",
                "WA",
                "WI",
                "WY",
                "ON",
                "QC",
                "NS",
                "NB",
                "MB",
                "BC",
                "PE",
                "SK",
                "AB",
                "NL",
                "NT",
                "YT",
                "UN",
                name="enum_nomina_ReceptorClaveEntFed",
            ),
            nullable=False,
        ),
        sa.Column("PercepcionesTotalSueldos", sa.Numeric(), nullable=True),
        sa.Column("PercepcionesTotalGravado", sa.Numeric(), nullable=True),
        sa.Column("PercepcionesTotalExento", sa.Numeric(), nullable=True),
        sa.Column("PercepcionesSeparacionIndemnizacion", sa.Numeric(), nullable=True),
        sa.Column("PercepcionesJubilacionPensionRetiro", sa.Numeric(), nullable=True),
        sa.Column("DeduccionesTotalOtrasDeducciones", sa.Numeric(), nullable=True),
        sa.Column("DeduccionesTotalImpuestosRetenidos", sa.Numeric(), nullable=True),
        sa.Column("SubsidioCausado", sa.Numeric(), nullable=True),
        sa.Column("AjusteISRRetenido", sa.Numeric(), nullable=True),
        sa.PrimaryKeyConstraint("cfdi_uuid"),
    )
    op.create_index(
        op.f("ix_nomina_EmisorRegistroPatronal"), "nomina", ["EmisorRegistroPatronal"], unique=False
    )
    op.create_index(op.f("ix_nomina_FechaFinalPago"), "nomina", ["FechaFinalPago"], unique=False)
    op.create_index(
        op.f("ix_nomina_FechaInicialPago"), "nomina", ["FechaInicialPago"], unique=False
    )
    op.create_index(op.f("ix_nomina_FechaPago"), "nomina", ["FechaPago"], unique=False)
    op.create_index(op.f("ix_nomina_ReceptorBanco"), "nomina", ["ReceptorBanco"], unique=False)
    op.create_index(
        op.f("ix_nomina_ReceptorClaveEntFed"), "nomina", ["ReceptorClaveEntFed"], unique=False
    )
    op.create_index(op.f("ix_nomina_ReceptorCurp"), "nomina", ["ReceptorCurp"], unique=False)
    op.create_index(
        op.f("ix_nomina_ReceptorDepartamento"), "nomina", ["ReceptorDepartamento"], unique=False
    )
    op.create_index(
        op.f("ix_nomina_ReceptorNumEmpleado"), "nomina", ["ReceptorNumEmpleado"], unique=False
    )
    op.create_index(
        op.f("ix_nomina_ReceptorNumSeguridadSocial"),
        "nomina",
        ["ReceptorNumSeguridadSocial"],
        unique=False,
    )
    op.create_index(
        op.f("ix_nomina_ReceptorPeriodicidadPago"),
        "nomina",
        ["ReceptorPeriodicidadPago"],
        unique=False,
    )
    op.create_index(op.f("ix_nomina_ReceptorPuesto"), "nomina", ["ReceptorPuesto"], unique=False)
    op.create_index(
        op.f("ix_nomina_ReceptorRiesgoPuesto"), "nomina", ["ReceptorRiesgoPuesto"], unique=False
    )
    op.create_index(
        op.f("ix_nomina_ReceptorTipoContrato"), "nomina", ["ReceptorTipoContrato"], unique=False
    )
    op.create_index(
        op.f("ix_nomina_ReceptorTipoJornada"), "nomina", ["ReceptorTipoJornada"], unique=False
    )
    op.create_index(
        op.f("ix_nomina_ReceptorTipoRegimen"), "nomina", ["ReceptorTipoRegimen"], unique=False
    )
    op.create_index(op.f("ix_nomina_TipoNomina"), "nomina", ["TipoNomina"], unique=False)
    op.create_index(op.f("ix_nomina_Version"), "nomina", ["Version"], unique=False)
    op.create_index(op.f("ix_nomina_cfdi_uuid"), "nomina", ["cfdi_uuid"], unique=False)
    op.create_table(
        "param",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", postgresql.UUID(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_param_identifier"), "param", ["identifier"], unique=True)
    op.create_index(op.f("ix_param_name"), "param", ["name"], unique=False)
    op.create_index(op.f("ix_param_value"), "param", ["value"], unique=False)
    op.create_table(
        "product",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("stripe_identifier", sa.String(), nullable=False),
        sa.Column("characteristics", sa.JSON(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("stripe_price_identifier", sa.String(), nullable=False),
        sa.Column("stripe_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("stripe_identifier"),
    )
    op.create_index(
        op.f("ix_product_stripe_identifier"), "product", ["stripe_identifier"], unique=False
    )
    op.create_index(op.f("ix_product_stripe_name"), "product", ["stripe_name"], unique=False)
    op.create_index(
        op.f("ix_product_stripe_price_identifier"),
        "product",
        ["stripe_price_identifier"],
        unique=False,
    )
    op.create_table(
        "scrap_result",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", postgresql.UUID(), nullable=True),
        sa.Column("rfc", sa.String(), nullable=False),
        sa.Column("start_date", sa.String(), nullable=False),
        sa.Column("end_date", sa.String(), nullable=False),
        sa.Column("download_type", sa.String(), nullable=False),
        sa.Column("request_type", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scrap_result_download_type"), "scrap_result", ["download_type"], unique=False
    )
    op.create_index(op.f("ix_scrap_result_end_date"), "scrap_result", ["end_date"], unique=False)
    op.create_index(op.f("ix_scrap_result_identifier"), "scrap_result", ["identifier"], unique=True)
    op.create_index(
        op.f("ix_scrap_result_request_type"), "scrap_result", ["request_type"], unique=False
    )
    op.create_index(op.f("ix_scrap_result_rfc"), "scrap_result", ["rfc"], unique=False)
    op.create_index(
        op.f("ix_scrap_result_start_date"), "scrap_result", ["start_date"], unique=False
    )
    op.create_table(
        "user",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", postgresql.UUID(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("cognito_sub", sa.String(), nullable=True),
        sa.Column("invited_by_id", sa.Integer(), nullable=True),
        sa.Column("source_name", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("odoo_identifier", sa.Integer(), nullable=True),
        sa.Column("stripe_identifier", sa.String(), nullable=True),
        sa.Column("stripe_subscription_identifier", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["invited_by_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_cognito_sub"), "user", ["cognito_sub"], unique=True)
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=False)
    op.create_index(op.f("ix_user_identifier"), "user", ["identifier"], unique=True)
    op.create_index(op.f("ix_user_invited_by_id"), "user", ["invited_by_id"], unique=False)
    op.create_index(op.f("ix_user_name"), "user", ["name"], unique=False)
    op.create_index(op.f("ix_user_source_name"), "user", ["source_name"], unique=False)
    op.create_table(
        "workspace",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", postgresql.UUID(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("license", sa.String(), nullable=True),
        sa.Column("valid_until", sa.DateTime(), nullable=True),
        sa.Column("odoo_id", sa.Integer(), nullable=True),
        sa.Column("stripe_status", sa.String(), nullable=True),
        sa.Column("pasto_worker_id", sa.String(), nullable=True),
        sa.Column("pasto_license_key", sa.String(), nullable=True),
        sa.Column("pasto_installed", sa.Boolean(), nullable=True),
        sa.Column("pasto_worker_token", sa.String(), nullable=True),
        sa.Column("add_permission", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workspace_add_permission"), "workspace", ["add_permission"], unique=False
    )
    op.create_index(op.f("ix_workspace_identifier"), "workspace", ["identifier"], unique=True)
    op.create_index(op.f("ix_workspace_license"), "workspace", ["license"], unique=False)
    op.create_index(op.f("ix_workspace_name"), "workspace", ["name"], unique=False)
    op.create_index(op.f("ix_workspace_odoo_id"), "workspace", ["odoo_id"], unique=False)
    op.create_index(op.f("ix_workspace_owner_id"), "workspace", ["owner_id"], unique=False)
    op.create_index(
        op.f("ix_workspace_pasto_license_key"), "workspace", ["pasto_license_key"], unique=True
    )
    op.create_index(
        op.f("ix_workspace_pasto_worker_id"), "workspace", ["pasto_worker_id"], unique=True
    )
    op.create_index(
        op.f("ix_workspace_stripe_status"), "workspace", ["stripe_status"], unique=False
    )
    op.create_index(op.f("ix_workspace_valid_until"), "workspace", ["valid_until"], unique=False)
    op.create_table(
        "notification_config",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", postgresql.UUID(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("workspace_identifier", postgresql.UUID(), nullable=True),
        sa.Column(
            "notification_type",
            sa.Enum("ERROR", "EFOS", "CANCELED", name="enum_notification_config_notification_type"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["workspace_identifier"], ["workspace.identifier"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_config_identifier"),
        "notification_config",
        ["identifier"],
        unique=True,
    )
    op.create_index(
        op.f("ix_notification_config_notification_type"),
        "notification_config",
        ["notification_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_config_user_id"), "notification_config", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_notification_config_workspace_id"),
        "notification_config",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_config_workspace_identifier"),
        "notification_config",
        ["workspace_identifier"],
        unique=False,
    )
    op.create_table(
        "pasto_company",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("pasto_company_id", postgresql.UUID(), nullable=False),
        sa.Column("workspace_identifier", postgresql.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("alias", sa.String(), nullable=False),
        sa.Column("rfc", sa.String(), nullable=False),
        sa.Column(
            "bdd", sa.String(), server_default="Base de datos no identificada", nullable=True
        ),
        sa.Column("system", sa.String(), server_default="Sistema no identificado", nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_identifier"], ["workspace.identifier"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("pasto_company_id"),
    )
    op.create_index(
        op.f("ix_pasto_company_pasto_company_id"),
        "pasto_company",
        ["pasto_company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pasto_company_workspace_identifier"),
        "pasto_company",
        ["workspace_identifier"],
        unique=False,
    )
    op.create_table(
        "company",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", postgresql.UUID(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=True),
        sa.Column("workspace_identifier", postgresql.UUID(), nullable=True),
        sa.Column("rfc", sa.String(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("have_certificates", sa.Boolean(), nullable=True),
        sa.Column("has_valid_certs", sa.Boolean(), nullable=True),
        sa.Column("emails_to_send_efos", sa.String(), nullable=True),
        sa.Column("emails_to_send_errors", sa.String(), nullable=True),
        sa.Column("emails_to_send_canceled", sa.String(), nullable=True),
        sa.Column("historic_downloaded", sa.Boolean(), nullable=True),
        sa.Column("last_ws_download", sa.DateTime(), nullable=True),
        sa.Column("exceed_metadata_limit", sa.Boolean(), nullable=False),
        sa.Column("permission_to_sync", sa.Boolean(), nullable=False),
        sa.Column("last_notification", sa.DateTime(), nullable=True),
        sa.Column("pasto_company_identifier", postgresql.UUID(), nullable=True),
        sa.Column("pasto_last_metadata_sync", sa.DateTime(), nullable=True),
        sa.Column("add_auto_sync", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["pasto_company_identifier"], ["pasto_company.pasto_company_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspace.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["workspace_identifier"], ["workspace.identifier"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_company_add_auto_sync"), "company", ["add_auto_sync"], unique=False)
    op.create_index(
        op.f("ix_company_has_valid_certs"), "company", ["has_valid_certs"], unique=False
    )
    op.create_index(
        op.f("ix_company_have_certificates"), "company", ["have_certificates"], unique=False
    )
    op.create_index(op.f("ix_company_identifier"), "company", ["identifier"], unique=True)
    op.create_index(op.f("ix_company_name"), "company", ["name"], unique=False)
    op.create_index(
        op.f("ix_company_pasto_company_identifier"),
        "company",
        ["pasto_company_identifier"],
        unique=False,
    )
    op.create_index(op.f("ix_company_rfc"), "company", ["rfc"], unique=False)
    op.create_index(op.f("ix_company_workspace_id"), "company", ["workspace_id"], unique=False)
    op.create_index(
        op.f("ix_company_workspace_identifier"), "company", ["workspace_identifier"], unique=False
    )
    op.create_table(
        "add_sync_request",
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("identifier", postgresql.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("start", sa.Date(), nullable=False),
        sa.Column("end", sa.Date(), nullable=False),
        sa.Column("xmls_to_send", sa.Integer(), nullable=False),
        sa.Column("xmls_to_send_pending", sa.Integer(), nullable=False),
        sa.Column("xmls_to_send_total", sa.Float(), nullable=False),
        sa.Column("cfdis_to_cancel", sa.Integer(), nullable=False),
        sa.Column("cfdis_to_cancel_pending", sa.Integer(), nullable=False),
        sa.Column("cfdis_to_cancel_total", sa.Float(), nullable=False),
        sa.Column("pasto_sent_identifier", postgresql.UUID(), nullable=True),
        sa.Column("pasto_cancel_identifier", postgresql.UUID(), nullable=True),
        sa.Column(
            "state",
            sa.Enum("DRAFT", "SENT", "ERROR", name="enum_add_sync_request_state"),
            nullable=False,
        ),
        sa.Column("manually_triggered", sa.Boolean(), server_default="false", nullable=False),
        sa.PrimaryKeyConstraint("identifier"),
    )
    op.create_index(
        op.f("ix_add_sync_request_created_at"), "add_sync_request", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_add_sync_request_state"), "add_sync_request", ["state"], unique=False)
    op.create_table(
        "cfdi",
        sa.Column("is_issued", sa.Boolean(), nullable=False),
        sa.Column("UUID", postgresql.UUID(), nullable=False),
        sa.Column("Fecha", sa.DateTime(), nullable=False),
        sa.Column("Total", sa.Numeric(), nullable=False),
        sa.Column("Folio", sa.String(), nullable=True),
        sa.Column("Serie", sa.String(), nullable=True),
        sa.Column("NoCertificado", sa.String(), nullable=True),
        sa.Column("Certificado", sa.String(), nullable=True),
        sa.Column("TipoDeComprobante", sa.String(), nullable=False),
        sa.Column("LugarExpedicion", sa.String(), nullable=True),
        sa.Column("FormaPago", sa.String(), nullable=True),
        sa.Column("MetodoPago", sa.String(), nullable=True),
        sa.Column("Moneda", sa.String(), nullable=True),
        sa.Column("SubTotal", sa.Numeric(), nullable=True),
        sa.Column("RfcEmisor", sa.String(), nullable=False),
        sa.Column("NombreEmisor", sa.String(), nullable=True),
        sa.Column("RfcReceptor", sa.String(), nullable=False),
        sa.Column("NombreReceptor", sa.String(), nullable=True),
        sa.Column("RfcPac", sa.String(), nullable=True),
        sa.Column("FechaCertificacionSat", sa.DateTime(), nullable=False),
        sa.Column("Estatus", sa.Boolean(), nullable=False),
        sa.Column("ExcludeFromIVA", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.Column("FechaCancelacion", sa.DateTime(), nullable=True),
        sa.Column("TipoCambio", sa.Numeric(), nullable=True),
        sa.Column("Conceptos", sa.String(), nullable=True),
        sa.Column("Version", sa.String(), nullable=True),
        sa.Column("Sello", sa.String(), nullable=True),
        sa.Column("UsoCFDIReceptor", sa.String(), nullable=True),
        sa.Column("RegimenFiscalEmisor", sa.String(), nullable=True),
        sa.Column("CondicionesDePago", sa.String(), nullable=True),
        sa.Column("CfdiRelacionados", sa.String(), nullable=True),
        sa.Column("Neto", sa.Numeric(), nullable=True),
        sa.Column("TrasladosIVA", sa.Numeric(), nullable=True),
        sa.Column("TrasladosIEPS", sa.Numeric(), nullable=True),
        sa.Column("TrasladosISR", sa.Numeric(), nullable=True),
        sa.Column("RetencionesIVA", sa.Numeric(), nullable=True),
        sa.Column("RetencionesIEPS", sa.Numeric(), nullable=True),
        sa.Column("RetencionesISR", sa.Numeric(), nullable=True),
        sa.Column("FechaFiltro", sa.DateTime(), nullable=False),
        sa.Column("Impuestos", sa.String(), nullable=True),
        sa.Column("Exportacion", sa.String(), nullable=True),
        sa.Column("Periodicidad", sa.String(), nullable=True),
        sa.Column("Meses", sa.String(), nullable=True),
        sa.Column("Year", sa.String(), nullable=True),
        sa.Column("DomicilioFiscalReceptor", sa.String(), nullable=True),
        sa.Column("RegimenFiscalReceptor", sa.String(), nullable=True),
        sa.Column("TotalMXN", sa.Numeric(), nullable=True),
        sa.Column("SubTotalMXN", sa.Numeric(), nullable=True),
        sa.Column("NetoMXN", sa.Numeric(), nullable=True),
        sa.Column("DescuentoMXN", sa.Numeric(), nullable=True),
        sa.Column("TrasladosIVAMXN", sa.Numeric(), nullable=True),
        sa.Column("TrasladosIEPSMXN", sa.Numeric(), nullable=True),
        sa.Column("TrasladosISRMXN", sa.Numeric(), nullable=True),
        sa.Column("RetencionesIVAMXN", sa.Numeric(), nullable=True),
        sa.Column("RetencionesIEPSMXN", sa.Numeric(), nullable=True),
        sa.Column("RetencionesISRMXN", sa.Numeric(), nullable=True),
        sa.Column("NoCertificadoSAT", sa.String(), nullable=True),
        sa.Column("SelloSAT", sa.String(), nullable=True),
        sa.Column("Descuento", sa.Numeric(), nullable=True),
        sa.Column("TipoDeComprobante_I_MetodoPago_PPD", sa.Boolean(), nullable=False),
        sa.Column("TipoDeComprobante_I_MetodoPago_PUE", sa.Boolean(), nullable=False),
        sa.Column("TipoDeComprobante_E_MetodoPago_PPD", sa.Boolean(), nullable=False),
        sa.Column("TipoDeComprobante_E_CfdiRelacionados_None", sa.Boolean(), nullable=False),
        sa.Column("cancelled_other_month", sa.Boolean(), nullable=False),
        sa.Column("other_rfc", sa.String(), nullable=True),
        sa.Column("balance", sa.Numeric(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("from_xml", sa.Boolean(), nullable=False),
        sa.Column("xml_content", XMLType(), nullable=True),
        sa.Column("add_exists", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.Column("add_cancel_date", sa.DateTime(), nullable=True),
        sa.Column("BaseIVA16", sa.Numeric(), nullable=True),
        sa.Column("BaseIVA8", sa.Numeric(), nullable=True),
        sa.Column("BaseIVA0", sa.Numeric(), nullable=True),
        sa.Column("BaseIVAExento", sa.Numeric(), nullable=True),
        sa.Column("IVATrasladado16", sa.Numeric(), nullable=True),
        sa.Column("IVATrasladado8", sa.Numeric(), nullable=True),
        sa.PrimaryKeyConstraint("is_issued", "UUID"),
    )
    op.create_index(op.f("ix_cfdi_FechaCancelacion"), "cfdi", ["FechaCancelacion"], unique=False)
    op.create_index(op.f("ix_cfdi_FechaFiltro"), "cfdi", ["FechaFiltro"], unique=False)
    op.create_index(op.f("ix_cfdi_MetodoPago"), "cfdi", ["MetodoPago"], unique=False)
    op.create_index(op.f("ix_cfdi_TipoDeComprobante"), "cfdi", ["TipoDeComprobante"], unique=False)
    op.create_index(op.f("ix_cfdi_UUID"), "cfdi", ["UUID"], unique=False)
    op.create_index(op.f("ix_cfdi_created_at"), "cfdi", ["created_at"], unique=False)
    op.create_index(op.f("ix_cfdi_other_rfc"), "cfdi", ["other_rfc"], unique=False)
    op.create_table(
        "payment",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("identifier", postgresql.UUID(), nullable=False),
        sa.Column("uuid_origin", postgresql.UUID(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("FechaPago", sa.DateTime(), nullable=False),
        sa.Column("FormaDePagoP", sa.String(), nullable=False),
        sa.Column("MonedaP", sa.String(), nullable=False),
        sa.Column("Monto", sa.Numeric(), nullable=False),
        sa.Column("TipoCambioP", sa.Numeric(), nullable=True),
        sa.Column("NumOperacion", sa.String(), nullable=True),
        sa.Column("RfcEmisorCtaOrd", sa.String(), nullable=True),
        sa.Column("NomBancoOrdExt", sa.String(), nullable=True),
        sa.Column("CtaOrdenante", sa.String(), nullable=True),
        sa.Column("RfcEmisorCtaBen", sa.String(), nullable=True),
        sa.Column("CtaBeneficiario", sa.String(), nullable=True),
        sa.Column("TipoCadPago", sa.String(), nullable=True),
        sa.Column("CertPago", sa.String(), nullable=True),
        sa.Column("CadPago", sa.String(), nullable=True),
        sa.Column("SelloPago", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("identifier"),
    )
    op.create_index(op.f("ix_payment_index"), "payment", ["index"], unique=False)
    op.create_index(op.f("ix_payment_uuid_origin"), "payment", ["uuid_origin"], unique=False)
    op.create_table(
        "payment_relation",
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("identifier", postgresql.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("payment_identifier", postgresql.UUID(), nullable=False),
        sa.Column("UUID", postgresql.UUID(), nullable=False),
        sa.Column("UUID_related", postgresql.UUID(), nullable=False),
        sa.Column("Folio", sa.String(), nullable=False),
        sa.Column("MonedaDR", sa.String(), nullable=False),
        sa.Column("MetodoDePagoDR", sa.String(), nullable=False),
        sa.Column("NumParcialidad", sa.Integer(), nullable=False),
        sa.Column("ImpSaldoAnt", sa.Numeric(), nullable=False),
        sa.Column("ImpPagado", sa.Numeric(), nullable=False),
        sa.Column("ImpSaldoInsoluto", sa.Numeric(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("applied", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("identifier"),
    )
    op.create_index(op.f("ix_payment_relation_UUID"), "payment_relation", ["UUID"], unique=False)
    op.create_index(
        op.f("ix_payment_relation_UUID_related"), "payment_relation", ["UUID_related"], unique=False
    )
    op.create_index(
        op.f("ix_payment_relation_created_at"), "payment_relation", ["created_at"], unique=False
    )
    op.create_table(
        "permission",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", postgresql.UUID(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column(
            "role", sa.Enum("OPERATOR", "PAYROLL", name="enum_permission_role"), nullable=False
        ),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_permission_company_id"), "permission", ["company_id"], unique=False)
    op.create_index(op.f("ix_permission_identifier"), "permission", ["identifier"], unique=True)
    op.create_index(op.f("ix_permission_role"), "permission", ["role"], unique=False)
    op.create_index(op.f("ix_permission_user_id"), "permission", ["user_id"], unique=False)
    op.create_table(
        "sat_query",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("identifier", postgresql.UUID(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("start", sa.DateTime(), nullable=False),
        sa.Column("end", sa.DateTime(), nullable=False),
        sa.Column(
            "download_type",
            sa.Enum("ISSUED", "RECEIVED", "BOTH", name="enum_sat_query_download_type"),
            nullable=False,
        ),
        sa.Column(
            "request_type",
            sa.Enum("CFDI", "METADATA", "BOTH", name="enum_sat_query_request_type"),
            nullable=False,
        ),
        sa.Column("packages", sa.String(), nullable=True),
        sa.Column("cfdis_qty", sa.Integer(), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "DRAFT",
                "SENT",
                "TO_DOWNLOAD",
                "DOWNLOADED",
                "TO_SCRAP",
                "DELAYED",
                "PROCESSING",
                "ERROR",
                "SCRAP_FAILED",
                "CANT_SCRAP",
                "TIME_LIMIT_REACHED",
                "MANUALLY_CANCELLED",
                "SPLITTED",
                "INFORMATION_NOT_FOUND",
                "SUBSTITUTED",
                "SUBSTITUTED_TO_SCRAP",
                "PROCESSED",
                "SCRAPPED",
                name="enum_sat_query_state",
            ),
            nullable=False,
        ),
        sa.Column("sent_date", sa.DateTime(), nullable=True),
        sa.Column("is_manual", sa.Boolean(), server_default="FALSE", nullable=True),
        sa.Column(
            "technology",
            sa.Enum("WebService", "Scraper", name="enum_sat_query_technology"),
            server_default="WebService",
            nullable=False,
        ),
        sa.Column("origin_identifier", postgresql.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["origin_identifier"], ["sat_query.identifier"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("identifier"),
    )
    op.create_index(op.f("ix_sat_query_company_id"), "sat_query", ["company_id"], unique=False)
    op.create_index(
        op.f("ix_sat_query_download_type"), "sat_query", ["download_type"], unique=False
    )
    op.create_index(op.f("ix_sat_query_end"), "sat_query", ["end"], unique=False)
    op.create_index(op.f("ix_sat_query_name"), "sat_query", ["name"], unique=False)
    op.create_index(op.f("ix_sat_query_packages"), "sat_query", ["packages"], unique=False)
    op.create_index(op.f("ix_sat_query_request_type"), "sat_query", ["request_type"], unique=False)
    op.create_index(op.f("ix_sat_query_sent_date"), "sat_query", ["sent_date"], unique=False)
    op.create_index(op.f("ix_sat_query_start"), "sat_query", ["start"], unique=False)
    op.create_index(op.f("ix_sat_query_state"), "sat_query", ["state"], unique=False)
    op.create_index(op.f("ix_sat_query_technology"), "sat_query", ["technology"], unique=False)
    op.create_table(
        "user_config",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", postgresql.UUID(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("data", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_config_company_id"), "user_config", ["company_id"], unique=False)
    op.create_index(op.f("ix_user_config_identifier"), "user_config", ["identifier"], unique=True)
    op.create_index(op.f("ix_user_config_user_id"), "user_config", ["user_id"], unique=False)
    op.create_table(
        "cfdi_export",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", postgresql.UUID(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column(
            "state", sa.Enum("SENT", "TO_DOWNLOAD", "ERROR", name="cfdiexportstate"), nullable=True
        ),
        sa.Column("expiration_date", sa.DateTime(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("start", sa.String(), nullable=True),
        sa.Column("end", sa.String(), nullable=True),
        sa.Column("cfdi_type", sa.String(), nullable=True),
        sa.Column("download_type", sa.String(), nullable=True),
        sa.Column("format", sa.String(), nullable=True),
        sa.Column("external_request", sa.Boolean(), nullable=True),
        sa.Column(
            "export_data_type",
            sa.Enum("CFDI", "IVA", name="exportdatatype"),
            server_default="CFDI",
            nullable=True,
        ),
        sa.Column("displayed_name", sa.String(), server_default="", nullable=False),
        sa.Column("file_name", sa.String(), server_default="", nullable=False),
        sa.Column("domain", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cfdi_export_url"), table_name="cfdi_export")
    op.drop_index(op.f("ix_cfdi_export_state"), table_name="cfdi_export")
    op.drop_index(op.f("ix_cfdi_export_start"), table_name="cfdi_export")
    op.drop_index(op.f("ix_cfdi_export_identifier"), table_name="cfdi_export")
    op.drop_index(op.f("ix_cfdi_export_format"), table_name="cfdi_export")
    op.drop_index(op.f("ix_cfdi_export_file_name"), table_name="cfdi_export")
    op.drop_index(op.f("ix_cfdi_export_export_data_type"), table_name="cfdi_export")
    op.drop_index(op.f("ix_cfdi_export_expiration_date"), table_name="cfdi_export")
    op.drop_index(op.f("ix_cfdi_export_end"), table_name="cfdi_export")
    op.drop_index(op.f("ix_cfdi_export_download_type"), table_name="cfdi_export")
    op.drop_index(op.f("ix_cfdi_export_displayed_name"), table_name="cfdi_export")
    op.drop_index(op.f("ix_cfdi_export_company_identifier"), table_name="cfdi_export")
    op.drop_index(op.f("ix_cfdi_export_company_id"), table_name="cfdi_export")
    op.drop_index(op.f("ix_cfdi_export_cfdi_type"), table_name="cfdi_export")
    op.drop_table("cfdi_export")
    op.drop_index(op.f("ix_user_config_user_id"), table_name="user_config")
    op.drop_index(op.f("ix_user_config_identifier"), table_name="user_config")
    op.drop_index(op.f("ix_user_config_company_id"), table_name="user_config")
    op.drop_table("user_config")
    op.drop_index(op.f("ix_sat_query_technology"), table_name="sat_query")
    op.drop_index(op.f("ix_sat_query_state"), table_name="sat_query")
    op.drop_index(op.f("ix_sat_query_start"), table_name="sat_query")
    op.drop_index(op.f("ix_sat_query_sent_date"), table_name="sat_query")
    op.drop_index(op.f("ix_sat_query_request_type"), table_name="sat_query")
    op.drop_index(op.f("ix_sat_query_packages"), table_name="sat_query")
    op.drop_index(op.f("ix_sat_query_name"), table_name="sat_query")
    op.drop_index(op.f("ix_sat_query_end"), table_name="sat_query")
    op.drop_index(op.f("ix_sat_query_download_type"), table_name="sat_query")
    op.drop_index(op.f("ix_sat_query_company_identifier"), table_name="sat_query")
    op.drop_table("sat_query")
    op.drop_index(op.f("ix_permission_user_id"), table_name="permission")
    op.drop_index(op.f("ix_permission_role"), table_name="permission")
    op.drop_index(op.f("ix_permission_identifier"), table_name="permission")
    op.drop_index(op.f("ix_permission_company_id"), table_name="permission")
    op.drop_table("permission")
    op.drop_index(op.f("ix_payment_relation_created_at"), table_name="payment_relation")
    op.drop_index(op.f("ix_payment_relation_company_identifier"), table_name="payment_relation")
    op.drop_index(op.f("ix_payment_relation_UUID_related"), table_name="payment_relation")
    op.drop_index(op.f("ix_payment_relation_UUID"), table_name="payment_relation")
    op.drop_table("payment_relation")
    op.drop_index(op.f("ix_payment_uuid_origin"), table_name="payment")
    op.drop_index(op.f("ix_payment_index"), table_name="payment")
    op.drop_index(op.f("ix_payment_company_identifier"), table_name="payment")
    op.drop_table("payment")
    op.drop_index(op.f("ix_cfdi_other_rfc"), table_name="cfdi")
    op.drop_index(op.f("ix_cfdi_created_at"), table_name="cfdi")
    op.drop_index(op.f("ix_cfdi_UUID"), table_name="cfdi")
    op.drop_index(op.f("ix_cfdi_TipoDeComprobante"), table_name="cfdi")
    op.drop_index(op.f("ix_cfdi_MetodoPago"), table_name="cfdi")
    op.drop_index(op.f("ix_cfdi_FechaFiltro"), table_name="cfdi")
    op.drop_index(op.f("ix_cfdi_FechaCancelacion"), table_name="cfdi")
    op.drop_table("cfdi")
    op.drop_index(op.f("ix_add_sync_request_state"), table_name="add_sync_request")
    op.drop_index(op.f("ix_add_sync_request_created_at"), table_name="add_sync_request")
    op.drop_index(op.f("ix_add_sync_request_company_identifier"), table_name="add_sync_request")
    op.drop_table("add_sync_request")
    op.drop_index(op.f("ix_company_workspace_identifier"), table_name="company")
    op.drop_index(op.f("ix_company_workspace_id"), table_name="company")
    op.drop_index(op.f("ix_company_rfc"), table_name="company")
    op.drop_index(op.f("ix_company_pasto_company_identifier"), table_name="company")
    op.drop_index(op.f("ix_company_name"), table_name="company")
    op.drop_index(op.f("ix_company_identifier"), table_name="company")
    op.drop_index(op.f("ix_company_have_certificates"), table_name="company")
    op.drop_index(op.f("ix_company_has_valid_certs"), table_name="company")
    op.drop_index(op.f("ix_company_add_auto_sync"), table_name="company")
    op.drop_table("company")
    op.drop_index(op.f("ix_pasto_company_workspace_identifier"), table_name="pasto_company")
    op.drop_index(op.f("ix_pasto_company_pasto_company_id"), table_name="pasto_company")
    op.drop_table("pasto_company")
    op.drop_index(
        op.f("ix_notification_config_workspace_identifier"), table_name="notification_config"
    )
    op.drop_index(op.f("ix_notification_config_workspace_id"), table_name="notification_config")
    op.drop_index(op.f("ix_notification_config_user_id"), table_name="notification_config")
    op.drop_index(
        op.f("ix_notification_config_notification_type"), table_name="notification_config"
    )
    op.drop_index(op.f("ix_notification_config_identifier"), table_name="notification_config")
    op.drop_table("notification_config")
    op.drop_index(op.f("ix_workspace_valid_until"), table_name="workspace")
    op.drop_index(op.f("ix_workspace_stripe_status"), table_name="workspace")
    op.drop_index(op.f("ix_workspace_pasto_worker_id"), table_name="workspace")
    op.drop_index(op.f("ix_workspace_pasto_license_key"), table_name="workspace")
    op.drop_index(op.f("ix_workspace_owner_id"), table_name="workspace")
    op.drop_index(op.f("ix_workspace_odoo_id"), table_name="workspace")
    op.drop_index(op.f("ix_workspace_name"), table_name="workspace")
    op.drop_index(op.f("ix_workspace_license"), table_name="workspace")
    op.drop_index(op.f("ix_workspace_identifier"), table_name="workspace")
    op.drop_index(op.f("ix_workspace_add_permission"), table_name="workspace")
    op.drop_table("workspace")
    op.drop_index(op.f("ix_user_source_name"), table_name="user")
    op.drop_index(op.f("ix_user_name"), table_name="user")
    op.drop_index(op.f("ix_user_invited_by_id"), table_name="user")
    op.drop_index(op.f("ix_user_identifier"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_index(op.f("ix_user_cognito_sub"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_scrap_result_start_date"), table_name="scrap_result")
    op.drop_index(op.f("ix_scrap_result_rfc"), table_name="scrap_result")
    op.drop_index(op.f("ix_scrap_result_request_type"), table_name="scrap_result")
    op.drop_index(op.f("ix_scrap_result_identifier"), table_name="scrap_result")
    op.drop_index(op.f("ix_scrap_result_end_date"), table_name="scrap_result")
    op.drop_index(op.f("ix_scrap_result_download_type"), table_name="scrap_result")
    op.drop_table("scrap_result")
    op.drop_index(op.f("ix_product_stripe_price_identifier"), table_name="product")
    op.drop_index(op.f("ix_product_stripe_name"), table_name="product")
    op.drop_index(op.f("ix_product_stripe_identifier"), table_name="product")
    op.drop_table("product")
    op.drop_index(op.f("ix_param_value"), table_name="param")
    op.drop_index(op.f("ix_param_name"), table_name="param")
    op.drop_index(op.f("ix_param_identifier"), table_name="param")
    op.drop_table("param")
    op.drop_index(op.f("ix_nomina_company_identifier"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_cfdi_uuid"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_Version"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_TipoNomina"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_ReceptorTipoRegimen"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_ReceptorTipoJornada"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_ReceptorTipoContrato"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_ReceptorRiesgoPuesto"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_ReceptorPuesto"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_ReceptorPeriodicidadPago"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_ReceptorNumSeguridadSocial"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_ReceptorNumEmpleado"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_ReceptorDepartamento"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_ReceptorCurp"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_ReceptorClaveEntFed"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_ReceptorBanco"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_FechaPago"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_FechaInicialPago"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_FechaFinalPago"), table_name="nomina")
    op.drop_index(op.f("ix_nomina_EmisorRegistroPatronal"), table_name="nomina")
    op.drop_table("nomina")
    op.drop_index(op.f("ix_efos_state"), table_name="efos")
    op.drop_index(op.f("ix_efos_rfc"), table_name="efos")
    op.drop_index(op.f("ix_efos_no"), table_name="efos")
    op.drop_index(op.f("ix_efos_name"), table_name="efos")
    op.drop_index(op.f("ix_efos_identifier"), table_name="efos")
    op.drop_table("efos")
    op.drop_index(op.f("ix_currency_symbol"), table_name="currency")
    op.drop_index(op.f("ix_currency_name"), table_name="currency")
    op.drop_index(op.f("ix_currency_identifier"), table_name="currency")
    op.drop_table("currency")
    op.drop_index(op.f("ix_cat_uso_cfdi_name"), table_name="cat_uso_cfdi")
    op.drop_index(op.f("ix_cat_uso_cfdi_identifier"), table_name="cat_uso_cfdi")
    op.drop_index(op.f("ix_cat_uso_cfdi_code"), table_name="cat_uso_cfdi")
    op.drop_table("cat_uso_cfdi")
    op.drop_index(op.f("ix_cat_tipo_relacion_name"), table_name="cat_tipo_relacion")
    op.drop_index(op.f("ix_cat_tipo_relacion_identifier"), table_name="cat_tipo_relacion")
    op.drop_index(op.f("ix_cat_tipo_relacion_code"), table_name="cat_tipo_relacion")
    op.drop_table("cat_tipo_relacion")
    op.drop_index(op.f("ix_cat_tipo_de_comprobante_name"), table_name="cat_tipo_de_comprobante")
    op.drop_index(
        op.f("ix_cat_tipo_de_comprobante_identifier"), table_name="cat_tipo_de_comprobante"
    )
    op.drop_index(op.f("ix_cat_tipo_de_comprobante_code"), table_name="cat_tipo_de_comprobante")
    op.drop_table("cat_tipo_de_comprobante")
    op.drop_index(op.f("ix_cat_regimen_fiscal_name"), table_name="cat_regimen_fiscal")
    op.drop_index(op.f("ix_cat_regimen_fiscal_identifier"), table_name="cat_regimen_fiscal")
    op.drop_index(op.f("ix_cat_regimen_fiscal_code"), table_name="cat_regimen_fiscal")
    op.drop_table("cat_regimen_fiscal")
    op.drop_index(op.f("ix_cat_periodicidad_name"), table_name="cat_periodicidad")
    op.drop_index(op.f("ix_cat_periodicidad_identifier"), table_name="cat_periodicidad")
    op.drop_index(op.f("ix_cat_periodicidad_code"), table_name="cat_periodicidad")
    op.drop_table("cat_periodicidad")
    op.drop_index(op.f("ix_cat_pais_name"), table_name="cat_pais")
    op.drop_index(op.f("ix_cat_pais_identifier"), table_name="cat_pais")
    op.drop_index(op.f("ix_cat_pais_code"), table_name="cat_pais")
    op.drop_table("cat_pais")
    op.drop_index(op.f("ix_cat_objeto_imp_name"), table_name="cat_objeto_imp")
    op.drop_index(op.f("ix_cat_objeto_imp_identifier"), table_name="cat_objeto_imp")
    op.drop_index(op.f("ix_cat_objeto_imp_code"), table_name="cat_objeto_imp")
    op.drop_table("cat_objeto_imp")
    op.drop_index(op.f("ix_cat_nom_tipo_regimen_name"), table_name="cat_nom_tipo_regimen")
    op.drop_index(op.f("ix_cat_nom_tipo_regimen_code"), table_name="cat_nom_tipo_regimen")
    op.drop_table("cat_nom_tipo_regimen")
    op.drop_index(op.f("ix_cat_nom_tipo_nomina_name"), table_name="cat_nom_tipo_nomina")
    op.drop_index(op.f("ix_cat_nom_tipo_nomina_code"), table_name="cat_nom_tipo_nomina")
    op.drop_table("cat_nom_tipo_nomina")
    op.drop_index(op.f("ix_cat_nom_tipo_jornada_name"), table_name="cat_nom_tipo_jornada")
    op.drop_index(op.f("ix_cat_nom_tipo_jornada_code"), table_name="cat_nom_tipo_jornada")
    op.drop_table("cat_nom_tipo_jornada")
    op.drop_index(op.f("ix_cat_nom_tipo_contrato_name"), table_name="cat_nom_tipo_contrato")
    op.drop_index(op.f("ix_cat_nom_tipo_contrato_code"), table_name="cat_nom_tipo_contrato")
    op.drop_table("cat_nom_tipo_contrato")
    op.drop_index(op.f("ix_cat_nom_riesgo_puesto_name"), table_name="cat_nom_riesgo_puesto")
    op.drop_index(op.f("ix_cat_nom_riesgo_puesto_code"), table_name="cat_nom_riesgo_puesto")
    op.drop_table("cat_nom_riesgo_puesto")
    op.drop_index(op.f("ix_cat_nom_periodicidad_pago_name"), table_name="cat_nom_periodicidad_pago")
    op.drop_index(op.f("ix_cat_nom_periodicidad_pago_code"), table_name="cat_nom_periodicidad_pago")
    op.drop_table("cat_nom_periodicidad_pago")
    op.drop_index(op.f("ix_cat_nom_clave_ent_fed_name"), table_name="cat_nom_clave_ent_fed")
    op.drop_index(op.f("ix_cat_nom_clave_ent_fed_code"), table_name="cat_nom_clave_ent_fed")
    op.drop_table("cat_nom_clave_ent_fed")
    op.drop_index(op.f("ix_cat_nom_banco_name"), table_name="cat_nom_banco")
    op.drop_index(op.f("ix_cat_nom_banco_code"), table_name="cat_nom_banco")
    op.drop_table("cat_nom_banco")
    op.drop_index(op.f("ix_cat_moneda_name"), table_name="cat_moneda")
    op.drop_index(op.f("ix_cat_moneda_identifier"), table_name="cat_moneda")
    op.drop_index(op.f("ix_cat_moneda_code"), table_name="cat_moneda")
    op.drop_table("cat_moneda")
    op.drop_index(op.f("ix_cat_metodo_pago_name"), table_name="cat_metodo_pago")
    op.drop_index(op.f("ix_cat_metodo_pago_identifier"), table_name="cat_metodo_pago")
    op.drop_index(op.f("ix_cat_metodo_pago_code"), table_name="cat_metodo_pago")
    op.drop_table("cat_metodo_pago")
    op.drop_index(op.f("ix_cat_meses_name"), table_name="cat_meses")
    op.drop_index(op.f("ix_cat_meses_identifier"), table_name="cat_meses")
    op.drop_index(op.f("ix_cat_meses_code"), table_name="cat_meses")
    op.drop_table("cat_meses")
    op.drop_index(op.f("ix_cat_impuesto_name"), table_name="cat_impuesto")
    op.drop_index(op.f("ix_cat_impuesto_identifier"), table_name="cat_impuesto")
    op.drop_index(op.f("ix_cat_impuesto_code"), table_name="cat_impuesto")
    op.drop_table("cat_impuesto")
    op.drop_index(op.f("ix_cat_forma_pago_name"), table_name="cat_forma_pago")
    op.drop_index(op.f("ix_cat_forma_pago_identifier"), table_name="cat_forma_pago")
    op.drop_index(op.f("ix_cat_forma_pago_code"), table_name="cat_forma_pago")
    op.drop_table("cat_forma_pago")
    op.drop_index(op.f("ix_cat_exportacion_name"), table_name="cat_exportacion")
    op.drop_index(op.f("ix_cat_exportacion_identifier"), table_name="cat_exportacion")
    op.drop_index(op.f("ix_cat_exportacion_code"), table_name="cat_exportacion")
    op.drop_table("cat_exportacion")
    op.drop_index(op.f("ix_cat_clave_unidad_name"), table_name="cat_clave_unidad")
    op.drop_index(op.f("ix_cat_clave_unidad_identifier"), table_name="cat_clave_unidad")
    op.drop_index(op.f("ix_cat_clave_unidad_code"), table_name="cat_clave_unidad")
    op.drop_table("cat_clave_unidad")
    op.drop_index(op.f("ix_cat_clave_prod_serv_name"), table_name="cat_clave_prod_serv")
    op.drop_index(op.f("ix_cat_clave_prod_serv_identifier"), table_name="cat_clave_prod_serv")
    op.drop_index(op.f("ix_cat_clave_prod_serv_code"), table_name="cat_clave_prod_serv")
    op.drop_table("cat_clave_prod_serv")
    op.drop_index(op.f("ix_cat_aduana_name"), table_name="cat_aduana")
    op.drop_index(op.f("ix_cat_aduana_identifier"), table_name="cat_aduana")
    op.drop_index(op.f("ix_cat_aduana_code"), table_name="cat_aduana")
    op.drop_table("cat_aduana")
    # ### end Alembic commands ###
