"""[ADD] PaymentDate

Revision ID: 6421279e87fa
Revises: 4c068081049f
Create Date: 2023-09-21 10:51:04.276906

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6421279e87fa"
down_revision = "4c068081049f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cfdi", sa.Column("PaymentDate", sa.DateTime(), nullable=False))
    op.create_index(op.f("ix_cfdi_PaymentDate"), "cfdi", ["PaymentDate"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cfdi_PaymentDate"), table_name="cfdi")
    op.drop_column("cfdi", "PaymentDate")
    # ### end Alembic commands ###
