"""new_data_column_on_company

Revision ID: 6808a553af10
Revises: 68093f3ae83f
Create Date: 2025-08-18 15:13:57.796467

"""

import json

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6808a553af10"
down_revision = "68093f3ae83f"
branch_labels = None
depends_on = None

# El valor por defecto que queremos establecer en la base de datos.
DEFAULT_DATA = {
    "scrap_status_constancy": {"current_status": "", "updated_at": ""},
    "scrap_status_order": {"current_status": "", "updated_at": ""},
}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company",
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text(f"'{json.dumps(DEFAULT_DATA)}'::jsonb"),
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("company", "data")
    # ### end Alembic commands ###
