"""Company.tenant_db_schema

Revision ID: 68093f3ae83f
Revises: 27ea151ac425
Create Date: 2025-07-15 10:59:18.879915

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "68093f3ae83f"
down_revision = "27ea151ac425"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("company", sa.Column("tenant_db_schema", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("company", "tenant_db_schema")
    # ### end Alembic commands ###
