"""empty message

Revision ID: 7d2222d8e845
Revises: 6421279e87fa
Create Date: 2023-10-10 09:51:39.722917

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "7d2222d8e845"
down_revision = "6421279e87fa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE exportdatatype ADD VALUE 'ISR'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE exportdatatype DROP VALUE 'ISR'")
    # ### end Alembic commands ###
