"""Remove UserConfig

Revision ID: 7ef244e7f1b6
Revises: 99b1a8ee93f0
Create Date: 2025-06-18 11:04:47.863897

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7ef244e7f1b6"
down_revision = "99b1a8ee93f0"
branch_labels = None
depends_on = None


def upgrade():
    return  # TODO restructuracion
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_config_company_id", table_name="user_config")
    op.drop_index("ix_user_config_identifier", table_name="user_config")
    op.drop_index("ix_user_config_user_id", table_name="user_config")
    op.drop_table("user_config")
    # ### end Alembic commands ###


def downgrade():
    return  # TODO restructuracion
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_config",
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("identifier", postgresql.UUID(), autoincrement=False, nullable=True),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("company_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("data", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"], ["company.id"], name="user_config_company_id_fkey", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="user_config_user_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="user_config_pkey"),
    )
    op.create_index("ix_user_config_user_id", "user_config", ["user_id"], unique=False)
    op.create_index("ix_user_config_identifier", "user_config", ["identifier"], unique=True)
    op.create_index("ix_user_config_company_id", "user_config", ["company_id"], unique=False)
    # ### end Alembic commands ###
