"""[ADD] ix_cfdi_need_xml

Revision ID: c211ab78636e
Revises: 4c0f3febf87b
Create Date: 2023-11-14 11:47:02.904294

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "c211ab78636e"
down_revision = "4c0f3febf87b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE INDEX ix_cfdi_need_xml
        ON cfdi(is_issued, "Estatus", from_xml, "Fecha")
        WHERE "Estatus" AND NOT from_xml;
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_cfdi_need_xml", table_name="cfdi")
    # ### end Alembic commands ###
