"""[IMP] sat_query.packages as JSON

Revision ID: d7e574841ff5
Revises: 3505313c9e03
Create Date: 2023-11-02 12:20:36.433370

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "d7e574841ff5"
down_revision = "3505313c9e03"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sat_query_packages", table_name="sat_query")
    op.execute("UPDATE sat_query SET packages = null")
    op.execute("ALTER TABLE sat_query ALTER COLUMN packages TYPE JSON USING packages::JSON")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE sat_query ALTER COLUMN packages TYPE TEXT USING packages::TEXT")
    op.create_index("ix_sat_query_packages", "sat_query", ["packages"], unique=False)
    # ### end Alembic commands ###
