"""Agregando columna is_too_big CFDI

Revision ID: e67bdb913f9f
Revises: 7cbf1ea158a4
Create Date: 2023-12-12 21:26:24.986625

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e67bdb913f9f"
down_revision = "7cbf1ea158a4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cfdi", sa.Column("is_too_big", sa.Boolean(), server_default="FALSE", nullable=False)
    )  # noqa E501
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cfdi", "is_too_big")
    # ### end Alembic commands ###
